package yk.boxri.pojo;

import java.io.Serializable;
import java.util.Date;


public class MyMessagesInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.message_id
     *
     * @mbggenerated
     */
    public String message_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.message_expiration_date
     *
     * @mbggenerated
     */
    public Date message_expiration_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.external_message_id
     *
     * @mbggenerated
     */
    public String external_message_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.message_flagged
     *
     * @mbggenerated
     */
    public Boolean message_flagged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.folde_id
     *
     * @mbggenerated
     */
    public Long folde_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.is_high_priority
     *
     * @mbggenerated
     */
    public Boolean is_high_priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.item_end_time
     *
     * @mbggenerated
     */
    public Date item_end_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.item_id
     *
     * @mbggenerated
     */
    public String item_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.item_title
     *
     * @mbggenerated
     */
    public String item_title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.listing_status
     *
     * @mbggenerated
     */
    public String listing_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.message_type
     *
     * @mbggenerated
     */
    public String message_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.question_type
     *
     * @mbggenerated
     */
    public String question_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.is_read
     *
     * @mbggenerated
     */
    public Boolean is_read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.receive_date
     *
     * @mbggenerated
     */
    public Date receive_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.recipient_user_id
     *
     * @mbggenerated
     */
    public String recipient_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.replied
     *
     * @mbggenerated
     */
    public Boolean replied;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.response_enabled
     *
     * @mbggenerated
     */
    public Boolean response_enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.response_URL
     *
     * @mbggenerated
     */
    public String response_URL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.sender
     *
     * @mbggenerated
     */
    public String sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.send_to_name
     *
     * @mbggenerated
     */
    public String send_to_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.subject
     *
     * @mbggenerated
     */
    public String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.transaction_id
     *
     * @mbggenerated
     */
    public String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.item_img_url
     *
     * @mbggenerated
     */
    public String item_img_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.order_status
     *
     * @mbggenerated
     */
    public String order_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.message_crm_status
     *
     * @mbggenerated
     */
    public Boolean message_crm_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.order_line_item_id
     *
     * @mbggenerated
     */
    public String order_line_item_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.message_content
     *
     * @mbggenerated
     */
    public String message_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_messages_info.text
     *
     * @mbggenerated
     */
    public String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_messages_info
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.message_id
     *
     * @return the value of my_messages_info.message_id
     *
     * @mbggenerated
     */
    public String getMessage_id() {
        return message_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.message_id
     *
     * @param message_id the value for my_messages_info.message_id
     *
     * @mbggenerated
     */
    public void setMessage_id(String message_id) {
        this.message_id = message_id == null ? null : message_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.user_id
     *
     * @return the value of my_messages_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.user_id
     *
     * @param user_id the value for my_messages_info.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.shop_id
     *
     * @return the value of my_messages_info.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.shop_id
     *
     * @param shop_id the value for my_messages_info.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.message_expiration_date
     *
     * @return the value of my_messages_info.message_expiration_date
     *
     * @mbggenerated
     */
    public Date getMessage_expiration_date() {
        return message_expiration_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.message_expiration_date
     *
     * @param message_expiration_date the value for my_messages_info.message_expiration_date
     *
     * @mbggenerated
     */
    public void setMessage_expiration_date(Date message_expiration_date) {
        this.message_expiration_date = message_expiration_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.external_message_id
     *
     * @return the value of my_messages_info.external_message_id
     *
     * @mbggenerated
     */
    public String getExternal_message_id() {
        return external_message_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.external_message_id
     *
     * @param external_message_id the value for my_messages_info.external_message_id
     *
     * @mbggenerated
     */
    public void setExternal_message_id(String external_message_id) {
        this.external_message_id = external_message_id == null ? null : external_message_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.message_flagged
     *
     * @return the value of my_messages_info.message_flagged
     *
     * @mbggenerated
     */
    public Boolean getMessage_flagged() {
        return message_flagged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.message_flagged
     *
     * @param message_flagged the value for my_messages_info.message_flagged
     *
     * @mbggenerated
     */
    public void setMessage_flagged(Boolean message_flagged) {
        this.message_flagged = message_flagged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.folde_id
     *
     * @return the value of my_messages_info.folde_id
     *
     * @mbggenerated
     */
    public Long getFolde_id() {
        return folde_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.folde_id
     *
     * @param folde_id the value for my_messages_info.folde_id
     *
     * @mbggenerated
     */
    public void setFolde_id(Long folde_id) {
        this.folde_id = folde_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.is_high_priority
     *
     * @return the value of my_messages_info.is_high_priority
     *
     * @mbggenerated
     */
    public Boolean getIs_high_priority() {
        return is_high_priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.is_high_priority
     *
     * @param is_high_priority the value for my_messages_info.is_high_priority
     *
     * @mbggenerated
     */
    public void setIs_high_priority(Boolean is_high_priority) {
        this.is_high_priority = is_high_priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.item_end_time
     *
     * @return the value of my_messages_info.item_end_time
     *
     * @mbggenerated
     */
    public Date getItem_end_time() {
        return item_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.item_end_time
     *
     * @param item_end_time the value for my_messages_info.item_end_time
     *
     * @mbggenerated
     */
    public void setItem_end_time(Date item_end_time) {
        this.item_end_time = item_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.item_id
     *
     * @return the value of my_messages_info.item_id
     *
     * @mbggenerated
     */
    public String getItem_id() {
        return item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.item_id
     *
     * @param item_id the value for my_messages_info.item_id
     *
     * @mbggenerated
     */
    public void setItem_id(String item_id) {
        this.item_id = item_id == null ? null : item_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.item_title
     *
     * @return the value of my_messages_info.item_title
     *
     * @mbggenerated
     */
    public String getItem_title() {
        return item_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.item_title
     *
     * @param item_title the value for my_messages_info.item_title
     *
     * @mbggenerated
     */
    public void setItem_title(String item_title) {
        this.item_title = item_title == null ? null : item_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.listing_status
     *
     * @return the value of my_messages_info.listing_status
     *
     * @mbggenerated
     */
    public String getListing_status() {
        return listing_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.listing_status
     *
     * @param listing_status the value for my_messages_info.listing_status
     *
     * @mbggenerated
     */
    public void setListing_status(String listing_status) {
        this.listing_status = listing_status == null ? null : listing_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.message_type
     *
     * @return the value of my_messages_info.message_type
     *
     * @mbggenerated
     */
    public String getMessage_type() {
        return message_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.message_type
     *
     * @param message_type the value for my_messages_info.message_type
     *
     * @mbggenerated
     */
    public void setMessage_type(String message_type) {
        this.message_type = message_type == null ? null : message_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.question_type
     *
     * @return the value of my_messages_info.question_type
     *
     * @mbggenerated
     */
    public String getQuestion_type() {
        return question_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.question_type
     *
     * @param question_type the value for my_messages_info.question_type
     *
     * @mbggenerated
     */
    public void setQuestion_type(String question_type) {
        this.question_type = question_type == null ? null : question_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.is_read
     *
     * @return the value of my_messages_info.is_read
     *
     * @mbggenerated
     */
    public Boolean getIs_read() {
        return is_read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.is_read
     *
     * @param is_read the value for my_messages_info.is_read
     *
     * @mbggenerated
     */
    public void setIs_read(Boolean is_read) {
        this.is_read = is_read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.receive_date
     *
     * @return the value of my_messages_info.receive_date
     *
     * @mbggenerated
     */
    public Date getReceive_date() {
        return receive_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.receive_date
     *
     * @param receive_date the value for my_messages_info.receive_date
     *
     * @mbggenerated
     */
    public void setReceive_date(Date receive_date) {
        this.receive_date = receive_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.recipient_user_id
     *
     * @return the value of my_messages_info.recipient_user_id
     *
     * @mbggenerated
     */
    public String getRecipient_user_id() {
        return recipient_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.recipient_user_id
     *
     * @param recipient_user_id the value for my_messages_info.recipient_user_id
     *
     * @mbggenerated
     */
    public void setRecipient_user_id(String recipient_user_id) {
        this.recipient_user_id = recipient_user_id == null ? null : recipient_user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.replied
     *
     * @return the value of my_messages_info.replied
     *
     * @mbggenerated
     */
    public Boolean getReplied() {
        return replied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.replied
     *
     * @param replied the value for my_messages_info.replied
     *
     * @mbggenerated
     */
    public void setReplied(Boolean replied) {
        this.replied = replied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.response_enabled
     *
     * @return the value of my_messages_info.response_enabled
     *
     * @mbggenerated
     */
    public Boolean getResponse_enabled() {
        return response_enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.response_enabled
     *
     * @param response_enabled the value for my_messages_info.response_enabled
     *
     * @mbggenerated
     */
    public void setResponse_enabled(Boolean response_enabled) {
        this.response_enabled = response_enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.response_URL
     *
     * @return the value of my_messages_info.response_URL
     *
     * @mbggenerated
     */
    public String getResponse_URL() {
        return response_URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.response_URL
     *
     * @param response_URL the value for my_messages_info.response_URL
     *
     * @mbggenerated
     */
    public void setResponse_URL(String response_URL) {
        this.response_URL = response_URL == null ? null : response_URL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.sender
     *
     * @return the value of my_messages_info.sender
     *
     * @mbggenerated
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.sender
     *
     * @param sender the value for my_messages_info.sender
     *
     * @mbggenerated
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.send_to_name
     *
     * @return the value of my_messages_info.send_to_name
     *
     * @mbggenerated
     */
    public String getSend_to_name() {
        return send_to_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.send_to_name
     *
     * @param send_to_name the value for my_messages_info.send_to_name
     *
     * @mbggenerated
     */
    public void setSend_to_name(String send_to_name) {
        this.send_to_name = send_to_name == null ? null : send_to_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.subject
     *
     * @return the value of my_messages_info.subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.subject
     *
     * @param subject the value for my_messages_info.subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.transaction_id
     *
     * @return the value of my_messages_info.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.transaction_id
     *
     * @param transaction_id the value for my_messages_info.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.item_img_url
     *
     * @return the value of my_messages_info.item_img_url
     *
     * @mbggenerated
     */
    public String getItem_img_url() {
        return item_img_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.item_img_url
     *
     * @param item_img_url the value for my_messages_info.item_img_url
     *
     * @mbggenerated
     */
    public void setItem_img_url(String item_img_url) {
        this.item_img_url = item_img_url == null ? null : item_img_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.order_status
     *
     * @return the value of my_messages_info.order_status
     *
     * @mbggenerated
     */
    public String getOrder_status() {
        return order_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.order_status
     *
     * @param order_status the value for my_messages_info.order_status
     *
     * @mbggenerated
     */
    public void setOrder_status(String order_status) {
        this.order_status = order_status == null ? null : order_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.order_id
     *
     * @return the value of my_messages_info.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.order_id
     *
     * @param order_id the value for my_messages_info.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.message_crm_status
     *
     * @return the value of my_messages_info.message_crm_status
     *
     * @mbggenerated
     */
    public Boolean getMessage_crm_status() {
        return message_crm_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.message_crm_status
     *
     * @param message_crm_status the value for my_messages_info.message_crm_status
     *
     * @mbggenerated
     */
    public void setMessage_crm_status(Boolean message_crm_status) {
        this.message_crm_status = message_crm_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.order_line_item_id
     *
     * @return the value of my_messages_info.order_line_item_id
     *
     * @mbggenerated
     */
    public String getOrder_line_item_id() {
        return order_line_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.order_line_item_id
     *
     * @param order_line_item_id the value for my_messages_info.order_line_item_id
     *
     * @mbggenerated
     */
    public void setOrder_line_item_id(String order_line_item_id) {
        this.order_line_item_id = order_line_item_id == null ? null : order_line_item_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.message_content
     *
     * @return the value of my_messages_info.message_content
     *
     * @mbggenerated
     */
    public String getMessage_content() {
        return message_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.message_content
     *
     * @param message_content the value for my_messages_info.message_content
     *
     * @mbggenerated
     */
    public void setMessage_content(String message_content) {
        this.message_content = message_content == null ? null : message_content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_messages_info.text
     *
     * @return the value of my_messages_info.text
     *
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_messages_info.text
     *
     * @param text the value for my_messages_info.text
     *
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}