package yk.boxri.pojo;

import java.io.Serializable;

public class OrderTransactionBuyer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_buyer.transaction_id
     *
     * @mbggenerated
     */
    public String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_buyer.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_buyer.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_buyer.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_buyer.buyer_tax_identifier
     *
     * @mbggenerated
     */
    public String buyer_tax_identifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_buyer.email
     *
     * @mbggenerated
     */
    public String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_buyer.static_alias
     *
     * @mbggenerated
     */
    public String static_alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_buyer.user_first_name
     *
     * @mbggenerated
     */
    public String user_first_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_buyer.user_last_name
     *
     * @mbggenerated
     */
    public String user_last_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_transaction_buyer
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_buyer.transaction_id
     *
     * @return the value of order_transaction_buyer.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_buyer.transaction_id
     *
     * @param transaction_id the value for order_transaction_buyer.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_buyer.order_id
     *
     * @return the value of order_transaction_buyer.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_buyer.order_id
     *
     * @param order_id the value for order_transaction_buyer.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_buyer.user_id
     *
     * @return the value of order_transaction_buyer.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_buyer.user_id
     *
     * @param user_id the value for order_transaction_buyer.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_buyer.shop_id
     *
     * @return the value of order_transaction_buyer.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_buyer.shop_id
     *
     * @param shop_id the value for order_transaction_buyer.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_buyer.buyer_tax_identifier
     *
     * @return the value of order_transaction_buyer.buyer_tax_identifier
     *
     * @mbggenerated
     */
    public String getBuyer_tax_identifier() {
        return buyer_tax_identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_buyer.buyer_tax_identifier
     *
     * @param buyer_tax_identifier the value for order_transaction_buyer.buyer_tax_identifier
     *
     * @mbggenerated
     */
    public void setBuyer_tax_identifier(String buyer_tax_identifier) {
        this.buyer_tax_identifier = buyer_tax_identifier == null ? null : buyer_tax_identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_buyer.email
     *
     * @return the value of order_transaction_buyer.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_buyer.email
     *
     * @param email the value for order_transaction_buyer.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_buyer.static_alias
     *
     * @return the value of order_transaction_buyer.static_alias
     *
     * @mbggenerated
     */
    public String getStatic_alias() {
        return static_alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_buyer.static_alias
     *
     * @param static_alias the value for order_transaction_buyer.static_alias
     *
     * @mbggenerated
     */
    public void setStatic_alias(String static_alias) {
        this.static_alias = static_alias == null ? null : static_alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_buyer.user_first_name
     *
     * @return the value of order_transaction_buyer.user_first_name
     *
     * @mbggenerated
     */
    public String getUser_first_name() {
        return user_first_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_buyer.user_first_name
     *
     * @param user_first_name the value for order_transaction_buyer.user_first_name
     *
     * @mbggenerated
     */
    public void setUser_first_name(String user_first_name) {
        this.user_first_name = user_first_name == null ? null : user_first_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_buyer.user_last_name
     *
     * @return the value of order_transaction_buyer.user_last_name
     *
     * @mbggenerated
     */
    public String getUser_last_name() {
        return user_last_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_buyer.user_last_name
     *
     * @param user_last_name the value for order_transaction_buyer.user_last_name
     *
     * @mbggenerated
     */
    public void setUser_last_name(String user_last_name) {
        this.user_last_name = user_last_name == null ? null : user_last_name.trim();
    }
}