package yk.boxri.pojo;

import java.io.Serializable;

public class OrderShippingDetailsIntlShippingServiceOption implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.order_shipping_details_intl_shipping_service_option_id
     *
     * @mbggenerated
     */
    public Integer order_shipping_details_intl_shipping_service_option_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.import_charge
     *
     * @mbggenerated
     */
    public Double import_charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.import_charge_currency_id
     *
     * @mbggenerated
     */
    public String import_charge_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.shipping_insurance_cost
     *
     * @mbggenerated
     */
    public Double shipping_insurance_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.shipping_insurance_cost_currency_id
     *
     * @mbggenerated
     */
    public String shipping_insurance_cost_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.shipping_service
     *
     * @mbggenerated
     */
    public String shipping_service;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.shipping_service_additional_cost
     *
     * @mbggenerated
     */
    public Double shipping_service_additional_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.shipping_service_additional_cost_currency_id
     *
     * @mbggenerated
     */
    public String shipping_service_additional_cost_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.shipping_service_cost
     *
     * @mbggenerated
     */
    public Double shipping_service_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.shipping_service__cost_currency_id
     *
     * @mbggenerated
     */
    public String shipping_service__cost_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.shipping_service_priority
     *
     * @mbggenerated
     */
    public Integer shipping_service_priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_intl_shipping_service_option.ship_to_location_values
     *
     * @mbggenerated
     */
    public String ship_to_location_values;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.order_id
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.order_id
     *
     * @param order_id the value for order_shipping_details_intl_shipping_service_option.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.order_shipping_details_intl_shipping_service_option_id
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.order_shipping_details_intl_shipping_service_option_id
     *
     * @mbggenerated
     */
    public Integer getOrder_shipping_details_intl_shipping_service_option_id() {
        return order_shipping_details_intl_shipping_service_option_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.order_shipping_details_intl_shipping_service_option_id
     *
     * @param order_shipping_details_intl_shipping_service_option_id the value for order_shipping_details_intl_shipping_service_option.order_shipping_details_intl_shipping_service_option_id
     *
     * @mbggenerated
     */
    public void setOrder_shipping_details_intl_shipping_service_option_id(Integer order_shipping_details_intl_shipping_service_option_id) {
        this.order_shipping_details_intl_shipping_service_option_id = order_shipping_details_intl_shipping_service_option_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.user_id
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.user_id
     *
     * @param user_id the value for order_shipping_details_intl_shipping_service_option.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.shop_id
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.shop_id
     *
     * @param shop_id the value for order_shipping_details_intl_shipping_service_option.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.import_charge
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.import_charge
     *
     * @mbggenerated
     */
    public Double getImport_charge() {
        return import_charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.import_charge
     *
     * @param import_charge the value for order_shipping_details_intl_shipping_service_option.import_charge
     *
     * @mbggenerated
     */
    public void setImport_charge(Double import_charge) {
        this.import_charge = import_charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.import_charge_currency_id
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.import_charge_currency_id
     *
     * @mbggenerated
     */
    public String getImport_charge_currency_id() {
        return import_charge_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.import_charge_currency_id
     *
     * @param import_charge_currency_id the value for order_shipping_details_intl_shipping_service_option.import_charge_currency_id
     *
     * @mbggenerated
     */
    public void setImport_charge_currency_id(String import_charge_currency_id) {
        this.import_charge_currency_id = import_charge_currency_id == null ? null : import_charge_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.shipping_insurance_cost
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.shipping_insurance_cost
     *
     * @mbggenerated
     */
    public Double getShipping_insurance_cost() {
        return shipping_insurance_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.shipping_insurance_cost
     *
     * @param shipping_insurance_cost the value for order_shipping_details_intl_shipping_service_option.shipping_insurance_cost
     *
     * @mbggenerated
     */
    public void setShipping_insurance_cost(Double shipping_insurance_cost) {
        this.shipping_insurance_cost = shipping_insurance_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.shipping_insurance_cost_currency_id
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.shipping_insurance_cost_currency_id
     *
     * @mbggenerated
     */
    public String getShipping_insurance_cost_currency_id() {
        return shipping_insurance_cost_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.shipping_insurance_cost_currency_id
     *
     * @param shipping_insurance_cost_currency_id the value for order_shipping_details_intl_shipping_service_option.shipping_insurance_cost_currency_id
     *
     * @mbggenerated
     */
    public void setShipping_insurance_cost_currency_id(String shipping_insurance_cost_currency_id) {
        this.shipping_insurance_cost_currency_id = shipping_insurance_cost_currency_id == null ? null : shipping_insurance_cost_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.shipping_service
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.shipping_service
     *
     * @mbggenerated
     */
    public String getShipping_service() {
        return shipping_service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.shipping_service
     *
     * @param shipping_service the value for order_shipping_details_intl_shipping_service_option.shipping_service
     *
     * @mbggenerated
     */
    public void setShipping_service(String shipping_service) {
        this.shipping_service = shipping_service == null ? null : shipping_service.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.shipping_service_additional_cost
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.shipping_service_additional_cost
     *
     * @mbggenerated
     */
    public Double getShipping_service_additional_cost() {
        return shipping_service_additional_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.shipping_service_additional_cost
     *
     * @param shipping_service_additional_cost the value for order_shipping_details_intl_shipping_service_option.shipping_service_additional_cost
     *
     * @mbggenerated
     */
    public void setShipping_service_additional_cost(Double shipping_service_additional_cost) {
        this.shipping_service_additional_cost = shipping_service_additional_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.shipping_service_additional_cost_currency_id
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.shipping_service_additional_cost_currency_id
     *
     * @mbggenerated
     */
    public String getShipping_service_additional_cost_currency_id() {
        return shipping_service_additional_cost_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.shipping_service_additional_cost_currency_id
     *
     * @param shipping_service_additional_cost_currency_id the value for order_shipping_details_intl_shipping_service_option.shipping_service_additional_cost_currency_id
     *
     * @mbggenerated
     */
    public void setShipping_service_additional_cost_currency_id(String shipping_service_additional_cost_currency_id) {
        this.shipping_service_additional_cost_currency_id = shipping_service_additional_cost_currency_id == null ? null : shipping_service_additional_cost_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.shipping_service_cost
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.shipping_service_cost
     *
     * @mbggenerated
     */
    public Double getShipping_service_cost() {
        return shipping_service_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.shipping_service_cost
     *
     * @param shipping_service_cost the value for order_shipping_details_intl_shipping_service_option.shipping_service_cost
     *
     * @mbggenerated
     */
    public void setShipping_service_cost(Double shipping_service_cost) {
        this.shipping_service_cost = shipping_service_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.shipping_service__cost_currency_id
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.shipping_service__cost_currency_id
     *
     * @mbggenerated
     */
    public String getShipping_service__cost_currency_id() {
        return shipping_service__cost_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.shipping_service__cost_currency_id
     *
     * @param shipping_service__cost_currency_id the value for order_shipping_details_intl_shipping_service_option.shipping_service__cost_currency_id
     *
     * @mbggenerated
     */
    public void setShipping_service__cost_currency_id(String shipping_service__cost_currency_id) {
        this.shipping_service__cost_currency_id = shipping_service__cost_currency_id == null ? null : shipping_service__cost_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.shipping_service_priority
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.shipping_service_priority
     *
     * @mbggenerated
     */
    public Integer getShipping_service_priority() {
        return shipping_service_priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.shipping_service_priority
     *
     * @param shipping_service_priority the value for order_shipping_details_intl_shipping_service_option.shipping_service_priority
     *
     * @mbggenerated
     */
    public void setShipping_service_priority(Integer shipping_service_priority) {
        this.shipping_service_priority = shipping_service_priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_intl_shipping_service_option.ship_to_location_values
     *
     * @return the value of order_shipping_details_intl_shipping_service_option.ship_to_location_values
     *
     * @mbggenerated
     */
    public String getShip_to_location_values() {
        return ship_to_location_values;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_intl_shipping_service_option.ship_to_location_values
     *
     * @param ship_to_location_values the value for order_shipping_details_intl_shipping_service_option.ship_to_location_values
     *
     * @mbggenerated
     */
    public void setShip_to_location_values(String ship_to_location_values) {
        this.ship_to_location_values = ship_to_location_values == null ? null : ship_to_location_values.trim();
    }
}