package yk.boxri.pojo;

import java.io.Serializable;
import java.util.Date;

public class OrderTransaction implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.transaction_id
     *
     * @mbggenerated
     */
    public String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.actual_handling_cost
     *
     * @mbggenerated
     */
    public Double actual_handling_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.actual_handling_cost_currency_id
     *
     * @mbggenerated
     */
    public String actual_handling_cost_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.actual_shipping_cost
     *
     * @mbggenerated
     */
    public Double actual_shipping_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.actual_shipping_cost_currency_id
     *
     * @mbggenerated
     */
    public String actual_shipping_cost_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.final_value_fee
     *
     * @mbggenerated
     */
    public Double final_value_fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.final_value_fee_currency_id
     *
     * @mbggenerated
     */
    public String final_value_fee_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.created_date
     *
     * @mbggenerated
     */
    public Date created_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.buyer_package_enclosures
     *
     * @mbggenerated
     */
    public String buyer_package_enclosures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.extended_order_id
     *
     * @mbggenerated
     */
    public String extended_order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.gift
     *
     * @mbggenerated
     */
    public Boolean gift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.gift_summary_message
     *
     * @mbggenerated
     */
    public String gift_summary_message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.guaranteed_shipping
     *
     * @mbggenerated
     */
    public Boolean guaranteed_shipping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.inventory_reservation_id
     *
     * @mbggenerated
     */
    public String inventory_reservation_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.invoice_sent_time
     *
     * @mbggenerated
     */
    public Date invoice_sent_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.listing_checkout_redirect_preference
     *
     * @mbggenerated
     */
    public String listing_checkout_redirect_preference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.logistics_plan_type
     *
     * @mbggenerated
     */
    public String logistics_plan_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.order_line_item_id
     *
     * @mbggenerated
     */
    public String order_line_item_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.shipping_convenience_charge
     *
     * @mbggenerated
     */
    public Double shipping_convenience_charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.shipping_convenience_charge_currency_id
     *
     * @mbggenerated
     */
    public String shipping_convenience_charge_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.paid_time
     *
     * @mbggenerated
     */
    public Date paid_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.quantity_purchased
     *
     * @mbggenerated
     */
    public Integer quantity_purchased;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.shipped_time
     *
     * @mbggenerated
     */
    public Date shipped_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.transaction_price
     *
     * @mbggenerated
     */
    public Double transaction_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.transaction_price_currency_id
     *
     * @mbggenerated
     */
    public String transaction_price_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.transaction_site_id
     *
     * @mbggenerated
     */
    public String transaction_site_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.status_digital_status
     *
     * @mbggenerated
     */
    public String status_digital_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.status_inquiry_status
     *
     * @mbggenerated
     */
    public String status_inquiry_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.status_integrated_merchant_credit_card_enabled
     *
     * @mbggenerated
     */
    public Boolean status_integrated_merchant_credit_card_enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.status_payment_hold_status
     *
     * @mbggenerated
     */
    public String status_payment_hold_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.status_payment_instrument
     *
     * @mbggenerated
     */
    public String status_payment_instrument;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.status_return_status
     *
     * @mbggenerated
     */
    public String status_return_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.unpaid_item_status
     *
     * @mbggenerated
     */
    public String unpaid_item_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.unpaiditem_type
     *
     * @mbggenerated
     */
    public String unpaiditem_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.pickup_method_selected_merchant_pickup_code
     *
     * @mbggenerated
     */
    public String pickup_method_selected_merchant_pickup_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.pickup_method_selected_pickup_fulfillment_time
     *
     * @mbggenerated
     */
    public Date pickup_method_selected_pickup_fulfillment_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.pickup_method_selected_pickup_location_UUID
     *
     * @mbggenerated
     */
    public String pickup_method_selected_pickup_location_UUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.pickup_method_selected_pickup_method
     *
     * @mbggenerated
     */
    public String pickup_method_selected_pickup_method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.pickup_method_selected_pickup_status
     *
     * @mbggenerated
     */
    public String pickup_method_selected_pickup_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.pickup_method_selected_pickup_store_id
     *
     * @mbggenerated
     */
    public String pickup_method_selected_pickup_store_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.order_transaction_unpaid_item_status
     *
     * @mbggenerated
     */
    public String order_transaction_unpaid_item_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction.order_transaction_unpaid_item_type
     *
     * @mbggenerated
     */
    public String order_transaction_unpaid_item_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_transaction
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.order_id
     *
     * @return the value of order_transaction.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.order_id
     *
     * @param order_id the value for order_transaction.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.transaction_id
     *
     * @return the value of order_transaction.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.transaction_id
     *
     * @param transaction_id the value for order_transaction.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.user_id
     *
     * @return the value of order_transaction.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.user_id
     *
     * @param user_id the value for order_transaction.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.shop_id
     *
     * @return the value of order_transaction.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.shop_id
     *
     * @param shop_id the value for order_transaction.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.actual_handling_cost
     *
     * @return the value of order_transaction.actual_handling_cost
     *
     * @mbggenerated
     */
    public Double getActual_handling_cost() {
        return actual_handling_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.actual_handling_cost
     *
     * @param actual_handling_cost the value for order_transaction.actual_handling_cost
     *
     * @mbggenerated
     */
    public void setActual_handling_cost(Double actual_handling_cost) {
        this.actual_handling_cost = actual_handling_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.actual_handling_cost_currency_id
     *
     * @return the value of order_transaction.actual_handling_cost_currency_id
     *
     * @mbggenerated
     */
    public String getActual_handling_cost_currency_id() {
        return actual_handling_cost_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.actual_handling_cost_currency_id
     *
     * @param actual_handling_cost_currency_id the value for order_transaction.actual_handling_cost_currency_id
     *
     * @mbggenerated
     */
    public void setActual_handling_cost_currency_id(String actual_handling_cost_currency_id) {
        this.actual_handling_cost_currency_id = actual_handling_cost_currency_id == null ? null : actual_handling_cost_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.actual_shipping_cost
     *
     * @return the value of order_transaction.actual_shipping_cost
     *
     * @mbggenerated
     */
    public Double getActual_shipping_cost() {
        return actual_shipping_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.actual_shipping_cost
     *
     * @param actual_shipping_cost the value for order_transaction.actual_shipping_cost
     *
     * @mbggenerated
     */
    public void setActual_shipping_cost(Double actual_shipping_cost) {
        this.actual_shipping_cost = actual_shipping_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.actual_shipping_cost_currency_id
     *
     * @return the value of order_transaction.actual_shipping_cost_currency_id
     *
     * @mbggenerated
     */
    public String getActual_shipping_cost_currency_id() {
        return actual_shipping_cost_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.actual_shipping_cost_currency_id
     *
     * @param actual_shipping_cost_currency_id the value for order_transaction.actual_shipping_cost_currency_id
     *
     * @mbggenerated
     */
    public void setActual_shipping_cost_currency_id(String actual_shipping_cost_currency_id) {
        this.actual_shipping_cost_currency_id = actual_shipping_cost_currency_id == null ? null : actual_shipping_cost_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.final_value_fee
     *
     * @return the value of order_transaction.final_value_fee
     *
     * @mbggenerated
     */
    public Double getFinal_value_fee() {
        return final_value_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.final_value_fee
     *
     * @param final_value_fee the value for order_transaction.final_value_fee
     *
     * @mbggenerated
     */
    public void setFinal_value_fee(Double final_value_fee) {
        this.final_value_fee = final_value_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.final_value_fee_currency_id
     *
     * @return the value of order_transaction.final_value_fee_currency_id
     *
     * @mbggenerated
     */
    public String getFinal_value_fee_currency_id() {
        return final_value_fee_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.final_value_fee_currency_id
     *
     * @param final_value_fee_currency_id the value for order_transaction.final_value_fee_currency_id
     *
     * @mbggenerated
     */
    public void setFinal_value_fee_currency_id(String final_value_fee_currency_id) {
        this.final_value_fee_currency_id = final_value_fee_currency_id == null ? null : final_value_fee_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.created_date
     *
     * @return the value of order_transaction.created_date
     *
     * @mbggenerated
     */
    public Date getCreated_date() {
        return created_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.created_date
     *
     * @param created_date the value for order_transaction.created_date
     *
     * @mbggenerated
     */
    public void setCreated_date(Date created_date) {
        this.created_date = created_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.buyer_package_enclosures
     *
     * @return the value of order_transaction.buyer_package_enclosures
     *
     * @mbggenerated
     */
    public String getBuyer_package_enclosures() {
        return buyer_package_enclosures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.buyer_package_enclosures
     *
     * @param buyer_package_enclosures the value for order_transaction.buyer_package_enclosures
     *
     * @mbggenerated
     */
    public void setBuyer_package_enclosures(String buyer_package_enclosures) {
        this.buyer_package_enclosures = buyer_package_enclosures == null ? null : buyer_package_enclosures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.extended_order_id
     *
     * @return the value of order_transaction.extended_order_id
     *
     * @mbggenerated
     */
    public String getExtended_order_id() {
        return extended_order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.extended_order_id
     *
     * @param extended_order_id the value for order_transaction.extended_order_id
     *
     * @mbggenerated
     */
    public void setExtended_order_id(String extended_order_id) {
        this.extended_order_id = extended_order_id == null ? null : extended_order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.gift
     *
     * @return the value of order_transaction.gift
     *
     * @mbggenerated
     */
    public Boolean getGift() {
        return gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.gift
     *
     * @param gift the value for order_transaction.gift
     *
     * @mbggenerated
     */
    public void setGift(Boolean gift) {
        this.gift = gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.gift_summary_message
     *
     * @return the value of order_transaction.gift_summary_message
     *
     * @mbggenerated
     */
    public String getGift_summary_message() {
        return gift_summary_message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.gift_summary_message
     *
     * @param gift_summary_message the value for order_transaction.gift_summary_message
     *
     * @mbggenerated
     */
    public void setGift_summary_message(String gift_summary_message) {
        this.gift_summary_message = gift_summary_message == null ? null : gift_summary_message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.guaranteed_shipping
     *
     * @return the value of order_transaction.guaranteed_shipping
     *
     * @mbggenerated
     */
    public Boolean getGuaranteed_shipping() {
        return guaranteed_shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.guaranteed_shipping
     *
     * @param guaranteed_shipping the value for order_transaction.guaranteed_shipping
     *
     * @mbggenerated
     */
    public void setGuaranteed_shipping(Boolean guaranteed_shipping) {
        this.guaranteed_shipping = guaranteed_shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.inventory_reservation_id
     *
     * @return the value of order_transaction.inventory_reservation_id
     *
     * @mbggenerated
     */
    public String getInventory_reservation_id() {
        return inventory_reservation_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.inventory_reservation_id
     *
     * @param inventory_reservation_id the value for order_transaction.inventory_reservation_id
     *
     * @mbggenerated
     */
    public void setInventory_reservation_id(String inventory_reservation_id) {
        this.inventory_reservation_id = inventory_reservation_id == null ? null : inventory_reservation_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.invoice_sent_time
     *
     * @return the value of order_transaction.invoice_sent_time
     *
     * @mbggenerated
     */
    public Date getInvoice_sent_time() {
        return invoice_sent_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.invoice_sent_time
     *
     * @param invoice_sent_time the value for order_transaction.invoice_sent_time
     *
     * @mbggenerated
     */
    public void setInvoice_sent_time(Date invoice_sent_time) {
        this.invoice_sent_time = invoice_sent_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.listing_checkout_redirect_preference
     *
     * @return the value of order_transaction.listing_checkout_redirect_preference
     *
     * @mbggenerated
     */
    public String getListing_checkout_redirect_preference() {
        return listing_checkout_redirect_preference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.listing_checkout_redirect_preference
     *
     * @param listing_checkout_redirect_preference the value for order_transaction.listing_checkout_redirect_preference
     *
     * @mbggenerated
     */
    public void setListing_checkout_redirect_preference(String listing_checkout_redirect_preference) {
        this.listing_checkout_redirect_preference = listing_checkout_redirect_preference == null ? null : listing_checkout_redirect_preference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.logistics_plan_type
     *
     * @return the value of order_transaction.logistics_plan_type
     *
     * @mbggenerated
     */
    public String getLogistics_plan_type() {
        return logistics_plan_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.logistics_plan_type
     *
     * @param logistics_plan_type the value for order_transaction.logistics_plan_type
     *
     * @mbggenerated
     */
    public void setLogistics_plan_type(String logistics_plan_type) {
        this.logistics_plan_type = logistics_plan_type == null ? null : logistics_plan_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.order_line_item_id
     *
     * @return the value of order_transaction.order_line_item_id
     *
     * @mbggenerated
     */
    public String getOrder_line_item_id() {
        return order_line_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.order_line_item_id
     *
     * @param order_line_item_id the value for order_transaction.order_line_item_id
     *
     * @mbggenerated
     */
    public void setOrder_line_item_id(String order_line_item_id) {
        this.order_line_item_id = order_line_item_id == null ? null : order_line_item_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.shipping_convenience_charge
     *
     * @return the value of order_transaction.shipping_convenience_charge
     *
     * @mbggenerated
     */
    public Double getShipping_convenience_charge() {
        return shipping_convenience_charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.shipping_convenience_charge
     *
     * @param shipping_convenience_charge the value for order_transaction.shipping_convenience_charge
     *
     * @mbggenerated
     */
    public void setShipping_convenience_charge(Double shipping_convenience_charge) {
        this.shipping_convenience_charge = shipping_convenience_charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.shipping_convenience_charge_currency_id
     *
     * @return the value of order_transaction.shipping_convenience_charge_currency_id
     *
     * @mbggenerated
     */
    public String getShipping_convenience_charge_currency_id() {
        return shipping_convenience_charge_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.shipping_convenience_charge_currency_id
     *
     * @param shipping_convenience_charge_currency_id the value for order_transaction.shipping_convenience_charge_currency_id
     *
     * @mbggenerated
     */
    public void setShipping_convenience_charge_currency_id(String shipping_convenience_charge_currency_id) {
        this.shipping_convenience_charge_currency_id = shipping_convenience_charge_currency_id == null ? null : shipping_convenience_charge_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.paid_time
     *
     * @return the value of order_transaction.paid_time
     *
     * @mbggenerated
     */
    public Date getPaid_time() {
        return paid_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.paid_time
     *
     * @param paid_time the value for order_transaction.paid_time
     *
     * @mbggenerated
     */
    public void setPaid_time(Date paid_time) {
        this.paid_time = paid_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.quantity_purchased
     *
     * @return the value of order_transaction.quantity_purchased
     *
     * @mbggenerated
     */
    public Integer getQuantity_purchased() {
        return quantity_purchased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.quantity_purchased
     *
     * @param quantity_purchased the value for order_transaction.quantity_purchased
     *
     * @mbggenerated
     */
    public void setQuantity_purchased(Integer quantity_purchased) {
        this.quantity_purchased = quantity_purchased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.shipped_time
     *
     * @return the value of order_transaction.shipped_time
     *
     * @mbggenerated
     */
    public Date getShipped_time() {
        return shipped_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.shipped_time
     *
     * @param shipped_time the value for order_transaction.shipped_time
     *
     * @mbggenerated
     */
    public void setShipped_time(Date shipped_time) {
        this.shipped_time = shipped_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.transaction_price
     *
     * @return the value of order_transaction.transaction_price
     *
     * @mbggenerated
     */
    public Double getTransaction_price() {
        return transaction_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.transaction_price
     *
     * @param transaction_price the value for order_transaction.transaction_price
     *
     * @mbggenerated
     */
    public void setTransaction_price(Double transaction_price) {
        this.transaction_price = transaction_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.transaction_price_currency_id
     *
     * @return the value of order_transaction.transaction_price_currency_id
     *
     * @mbggenerated
     */
    public String getTransaction_price_currency_id() {
        return transaction_price_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.transaction_price_currency_id
     *
     * @param transaction_price_currency_id the value for order_transaction.transaction_price_currency_id
     *
     * @mbggenerated
     */
    public void setTransaction_price_currency_id(String transaction_price_currency_id) {
        this.transaction_price_currency_id = transaction_price_currency_id == null ? null : transaction_price_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.transaction_site_id
     *
     * @return the value of order_transaction.transaction_site_id
     *
     * @mbggenerated
     */
    public String getTransaction_site_id() {
        return transaction_site_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.transaction_site_id
     *
     * @param transaction_site_id the value for order_transaction.transaction_site_id
     *
     * @mbggenerated
     */
    public void setTransaction_site_id(String transaction_site_id) {
        this.transaction_site_id = transaction_site_id == null ? null : transaction_site_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.status_digital_status
     *
     * @return the value of order_transaction.status_digital_status
     *
     * @mbggenerated
     */
    public String getStatus_digital_status() {
        return status_digital_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.status_digital_status
     *
     * @param status_digital_status the value for order_transaction.status_digital_status
     *
     * @mbggenerated
     */
    public void setStatus_digital_status(String status_digital_status) {
        this.status_digital_status = status_digital_status == null ? null : status_digital_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.status_inquiry_status
     *
     * @return the value of order_transaction.status_inquiry_status
     *
     * @mbggenerated
     */
    public String getStatus_inquiry_status() {
        return status_inquiry_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.status_inquiry_status
     *
     * @param status_inquiry_status the value for order_transaction.status_inquiry_status
     *
     * @mbggenerated
     */
    public void setStatus_inquiry_status(String status_inquiry_status) {
        this.status_inquiry_status = status_inquiry_status == null ? null : status_inquiry_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.status_integrated_merchant_credit_card_enabled
     *
     * @return the value of order_transaction.status_integrated_merchant_credit_card_enabled
     *
     * @mbggenerated
     */
    public Boolean getStatus_integrated_merchant_credit_card_enabled() {
        return status_integrated_merchant_credit_card_enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.status_integrated_merchant_credit_card_enabled
     *
     * @param status_integrated_merchant_credit_card_enabled the value for order_transaction.status_integrated_merchant_credit_card_enabled
     *
     * @mbggenerated
     */
    public void setStatus_integrated_merchant_credit_card_enabled(Boolean status_integrated_merchant_credit_card_enabled) {
        this.status_integrated_merchant_credit_card_enabled = status_integrated_merchant_credit_card_enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.status_payment_hold_status
     *
     * @return the value of order_transaction.status_payment_hold_status
     *
     * @mbggenerated
     */
    public String getStatus_payment_hold_status() {
        return status_payment_hold_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.status_payment_hold_status
     *
     * @param status_payment_hold_status the value for order_transaction.status_payment_hold_status
     *
     * @mbggenerated
     */
    public void setStatus_payment_hold_status(String status_payment_hold_status) {
        this.status_payment_hold_status = status_payment_hold_status == null ? null : status_payment_hold_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.status_payment_instrument
     *
     * @return the value of order_transaction.status_payment_instrument
     *
     * @mbggenerated
     */
    public String getStatus_payment_instrument() {
        return status_payment_instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.status_payment_instrument
     *
     * @param status_payment_instrument the value for order_transaction.status_payment_instrument
     *
     * @mbggenerated
     */
    public void setStatus_payment_instrument(String status_payment_instrument) {
        this.status_payment_instrument = status_payment_instrument == null ? null : status_payment_instrument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.status_return_status
     *
     * @return the value of order_transaction.status_return_status
     *
     * @mbggenerated
     */
    public String getStatus_return_status() {
        return status_return_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.status_return_status
     *
     * @param status_return_status the value for order_transaction.status_return_status
     *
     * @mbggenerated
     */
    public void setStatus_return_status(String status_return_status) {
        this.status_return_status = status_return_status == null ? null : status_return_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.unpaid_item_status
     *
     * @return the value of order_transaction.unpaid_item_status
     *
     * @mbggenerated
     */
    public String getUnpaid_item_status() {
        return unpaid_item_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.unpaid_item_status
     *
     * @param unpaid_item_status the value for order_transaction.unpaid_item_status
     *
     * @mbggenerated
     */
    public void setUnpaid_item_status(String unpaid_item_status) {
        this.unpaid_item_status = unpaid_item_status == null ? null : unpaid_item_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.unpaiditem_type
     *
     * @return the value of order_transaction.unpaiditem_type
     *
     * @mbggenerated
     */
    public String getUnpaiditem_type() {
        return unpaiditem_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.unpaiditem_type
     *
     * @param unpaiditem_type the value for order_transaction.unpaiditem_type
     *
     * @mbggenerated
     */
    public void setUnpaiditem_type(String unpaiditem_type) {
        this.unpaiditem_type = unpaiditem_type == null ? null : unpaiditem_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.pickup_method_selected_merchant_pickup_code
     *
     * @return the value of order_transaction.pickup_method_selected_merchant_pickup_code
     *
     * @mbggenerated
     */
    public String getPickup_method_selected_merchant_pickup_code() {
        return pickup_method_selected_merchant_pickup_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.pickup_method_selected_merchant_pickup_code
     *
     * @param pickup_method_selected_merchant_pickup_code the value for order_transaction.pickup_method_selected_merchant_pickup_code
     *
     * @mbggenerated
     */
    public void setPickup_method_selected_merchant_pickup_code(String pickup_method_selected_merchant_pickup_code) {
        this.pickup_method_selected_merchant_pickup_code = pickup_method_selected_merchant_pickup_code == null ? null : pickup_method_selected_merchant_pickup_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.pickup_method_selected_pickup_fulfillment_time
     *
     * @return the value of order_transaction.pickup_method_selected_pickup_fulfillment_time
     *
     * @mbggenerated
     */
    public Date getPickup_method_selected_pickup_fulfillment_time() {
        return pickup_method_selected_pickup_fulfillment_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.pickup_method_selected_pickup_fulfillment_time
     *
     * @param pickup_method_selected_pickup_fulfillment_time the value for order_transaction.pickup_method_selected_pickup_fulfillment_time
     *
     * @mbggenerated
     */
    public void setPickup_method_selected_pickup_fulfillment_time(Date pickup_method_selected_pickup_fulfillment_time) {
        this.pickup_method_selected_pickup_fulfillment_time = pickup_method_selected_pickup_fulfillment_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.pickup_method_selected_pickup_location_UUID
     *
     * @return the value of order_transaction.pickup_method_selected_pickup_location_UUID
     *
     * @mbggenerated
     */
    public String getPickup_method_selected_pickup_location_UUID() {
        return pickup_method_selected_pickup_location_UUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.pickup_method_selected_pickup_location_UUID
     *
     * @param pickup_method_selected_pickup_location_UUID the value for order_transaction.pickup_method_selected_pickup_location_UUID
     *
     * @mbggenerated
     */
    public void setPickup_method_selected_pickup_location_UUID(String pickup_method_selected_pickup_location_UUID) {
        this.pickup_method_selected_pickup_location_UUID = pickup_method_selected_pickup_location_UUID == null ? null : pickup_method_selected_pickup_location_UUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.pickup_method_selected_pickup_method
     *
     * @return the value of order_transaction.pickup_method_selected_pickup_method
     *
     * @mbggenerated
     */
    public String getPickup_method_selected_pickup_method() {
        return pickup_method_selected_pickup_method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.pickup_method_selected_pickup_method
     *
     * @param pickup_method_selected_pickup_method the value for order_transaction.pickup_method_selected_pickup_method
     *
     * @mbggenerated
     */
    public void setPickup_method_selected_pickup_method(String pickup_method_selected_pickup_method) {
        this.pickup_method_selected_pickup_method = pickup_method_selected_pickup_method == null ? null : pickup_method_selected_pickup_method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.pickup_method_selected_pickup_status
     *
     * @return the value of order_transaction.pickup_method_selected_pickup_status
     *
     * @mbggenerated
     */
    public String getPickup_method_selected_pickup_status() {
        return pickup_method_selected_pickup_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.pickup_method_selected_pickup_status
     *
     * @param pickup_method_selected_pickup_status the value for order_transaction.pickup_method_selected_pickup_status
     *
     * @mbggenerated
     */
    public void setPickup_method_selected_pickup_status(String pickup_method_selected_pickup_status) {
        this.pickup_method_selected_pickup_status = pickup_method_selected_pickup_status == null ? null : pickup_method_selected_pickup_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.pickup_method_selected_pickup_store_id
     *
     * @return the value of order_transaction.pickup_method_selected_pickup_store_id
     *
     * @mbggenerated
     */
    public String getPickup_method_selected_pickup_store_id() {
        return pickup_method_selected_pickup_store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.pickup_method_selected_pickup_store_id
     *
     * @param pickup_method_selected_pickup_store_id the value for order_transaction.pickup_method_selected_pickup_store_id
     *
     * @mbggenerated
     */
    public void setPickup_method_selected_pickup_store_id(String pickup_method_selected_pickup_store_id) {
        this.pickup_method_selected_pickup_store_id = pickup_method_selected_pickup_store_id == null ? null : pickup_method_selected_pickup_store_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.order_transaction_unpaid_item_status
     *
     * @return the value of order_transaction.order_transaction_unpaid_item_status
     *
     * @mbggenerated
     */
    public String getOrder_transaction_unpaid_item_status() {
        return order_transaction_unpaid_item_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.order_transaction_unpaid_item_status
     *
     * @param order_transaction_unpaid_item_status the value for order_transaction.order_transaction_unpaid_item_status
     *
     * @mbggenerated
     */
    public void setOrder_transaction_unpaid_item_status(String order_transaction_unpaid_item_status) {
        this.order_transaction_unpaid_item_status = order_transaction_unpaid_item_status == null ? null : order_transaction_unpaid_item_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction.order_transaction_unpaid_item_type
     *
     * @return the value of order_transaction.order_transaction_unpaid_item_type
     *
     * @mbggenerated
     */
    public String getOrder_transaction_unpaid_item_type() {
        return order_transaction_unpaid_item_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction.order_transaction_unpaid_item_type
     *
     * @param order_transaction_unpaid_item_type the value for order_transaction.order_transaction_unpaid_item_type
     *
     * @mbggenerated
     */
    public void setOrder_transaction_unpaid_item_type(String order_transaction_unpaid_item_type) {
        this.order_transaction_unpaid_item_type = order_transaction_unpaid_item_type == null ? null : order_transaction_unpaid_item_type.trim();
    }
}