package yk.boxri.pojo;

import java.io.Serializable;
import java.util.Date;

public class OrderRefundArray implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund_array.refund_id
     *
     * @mbggenerated
     */
    public String refund_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund_array.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund_array.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund_array.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund_array.refund_amount
     *
     * @mbggenerated
     */
    public Double refund_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund_array.refund_amount_currency_id
     *
     * @mbggenerated
     */
    public String refund_amount_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund_array.refund_from_seller
     *
     * @mbggenerated
     */
    public Double refund_from_seller;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund_array.refund_from_seller_currency_id
     *
     * @mbggenerated
     */
    public String refund_from_seller_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund_array.refund_time
     *
     * @mbggenerated
     */
    public Date refund_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund_array.total_refund_to_buyer
     *
     * @mbggenerated
     */
    public Double total_refund_to_buyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund_array.total_refund_to_buyer_currency_id
     *
     * @mbggenerated
     */
    public String total_refund_to_buyer_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_refund_array
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund_array.refund_id
     *
     * @return the value of order_refund_array.refund_id
     *
     * @mbggenerated
     */
    public String getRefund_id() {
        return refund_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund_array.refund_id
     *
     * @param refund_id the value for order_refund_array.refund_id
     *
     * @mbggenerated
     */
    public void setRefund_id(String refund_id) {
        this.refund_id = refund_id == null ? null : refund_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund_array.order_id
     *
     * @return the value of order_refund_array.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund_array.order_id
     *
     * @param order_id the value for order_refund_array.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund_array.user_id
     *
     * @return the value of order_refund_array.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund_array.user_id
     *
     * @param user_id the value for order_refund_array.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund_array.shop_id
     *
     * @return the value of order_refund_array.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund_array.shop_id
     *
     * @param shop_id the value for order_refund_array.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund_array.refund_amount
     *
     * @return the value of order_refund_array.refund_amount
     *
     * @mbggenerated
     */
    public Double getRefund_amount() {
        return refund_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund_array.refund_amount
     *
     * @param refund_amount the value for order_refund_array.refund_amount
     *
     * @mbggenerated
     */
    public void setRefund_amount(Double refund_amount) {
        this.refund_amount = refund_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund_array.refund_amount_currency_id
     *
     * @return the value of order_refund_array.refund_amount_currency_id
     *
     * @mbggenerated
     */
    public String getRefund_amount_currency_id() {
        return refund_amount_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund_array.refund_amount_currency_id
     *
     * @param refund_amount_currency_id the value for order_refund_array.refund_amount_currency_id
     *
     * @mbggenerated
     */
    public void setRefund_amount_currency_id(String refund_amount_currency_id) {
        this.refund_amount_currency_id = refund_amount_currency_id == null ? null : refund_amount_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund_array.refund_from_seller
     *
     * @return the value of order_refund_array.refund_from_seller
     *
     * @mbggenerated
     */
    public Double getRefund_from_seller() {
        return refund_from_seller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund_array.refund_from_seller
     *
     * @param refund_from_seller the value for order_refund_array.refund_from_seller
     *
     * @mbggenerated
     */
    public void setRefund_from_seller(Double refund_from_seller) {
        this.refund_from_seller = refund_from_seller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund_array.refund_from_seller_currency_id
     *
     * @return the value of order_refund_array.refund_from_seller_currency_id
     *
     * @mbggenerated
     */
    public String getRefund_from_seller_currency_id() {
        return refund_from_seller_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund_array.refund_from_seller_currency_id
     *
     * @param refund_from_seller_currency_id the value for order_refund_array.refund_from_seller_currency_id
     *
     * @mbggenerated
     */
    public void setRefund_from_seller_currency_id(String refund_from_seller_currency_id) {
        this.refund_from_seller_currency_id = refund_from_seller_currency_id == null ? null : refund_from_seller_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund_array.refund_time
     *
     * @return the value of order_refund_array.refund_time
     *
     * @mbggenerated
     */
    public Date getRefund_time() {
        return refund_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund_array.refund_time
     *
     * @param refund_time the value for order_refund_array.refund_time
     *
     * @mbggenerated
     */
    public void setRefund_time(Date refund_time) {
        this.refund_time = refund_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund_array.total_refund_to_buyer
     *
     * @return the value of order_refund_array.total_refund_to_buyer
     *
     * @mbggenerated
     */
    public Double getTotal_refund_to_buyer() {
        return total_refund_to_buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund_array.total_refund_to_buyer
     *
     * @param total_refund_to_buyer the value for order_refund_array.total_refund_to_buyer
     *
     * @mbggenerated
     */
    public void setTotal_refund_to_buyer(Double total_refund_to_buyer) {
        this.total_refund_to_buyer = total_refund_to_buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund_array.total_refund_to_buyer_currency_id
     *
     * @return the value of order_refund_array.total_refund_to_buyer_currency_id
     *
     * @mbggenerated
     */
    public String getTotal_refund_to_buyer_currency_id() {
        return total_refund_to_buyer_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund_array.total_refund_to_buyer_currency_id
     *
     * @param total_refund_to_buyer_currency_id the value for order_refund_array.total_refund_to_buyer_currency_id
     *
     * @mbggenerated
     */
    public void setTotal_refund_to_buyer_currency_id(String total_refund_to_buyer_currency_id) {
        this.total_refund_to_buyer_currency_id = total_refund_to_buyer_currency_id == null ? null : total_refund_to_buyer_currency_id.trim();
    }
}