package yk.boxri.pojo;

import java.io.Serializable;

public class OrderTransactionShippingDetails implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.transaction_id
     *
     * @mbggenerated
     */
    public String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.international_packaging_handling_costs
     *
     * @mbggenerated
     */
    public Double international_packaging_handling_costs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.international_packaging_handling_costs_currency_id
     *
     * @mbggenerated
     */
    public String international_packaging_handling_costs_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.originating_postal_code
     *
     * @mbggenerated
     */
    public String originating_postal_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.packaging_handling_costs
     *
     * @mbggenerated
     */
    public Double packaging_handling_costs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.packaging_handling_costs_currency_id
     *
     * @mbggenerated
     */
    public String packaging_handling_costs_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.shipping_irregular
     *
     * @mbggenerated
     */
    public Boolean shipping_irregular;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.COD_cost
     *
     * @mbggenerated
     */
    public Double COD_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.COD_cost_currency_id
     *
     * @mbggenerated
     */
    public String COD_cost_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.insurance_wanted
     *
     * @mbggenerated
     */
    public Boolean insurance_wanted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.sales_tax_amount
     *
     * @mbggenerated
     */
    public Double sales_tax_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.sales_tax_amount_currency_id
     *
     * @mbggenerated
     */
    public String sales_tax_amount_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.sales_tax_percent
     *
     * @mbggenerated
     */
    public Float sales_tax_percent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.sales_tax_state
     *
     * @mbggenerated
     */
    public String sales_tax_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.shipping_included_in_tax
     *
     * @mbggenerated
     */
    public Boolean shipping_included_in_tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.selling_manager_sales_record_number
     *
     * @mbggenerated
     */
    public Integer selling_manager_sales_record_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_shipping_details.tax_jurisdiction
     *
     * @mbggenerated
     */
    public String tax_jurisdiction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_transaction_shipping_details
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.transaction_id
     *
     * @return the value of order_transaction_shipping_details.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.transaction_id
     *
     * @param transaction_id the value for order_transaction_shipping_details.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.order_id
     *
     * @return the value of order_transaction_shipping_details.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.order_id
     *
     * @param order_id the value for order_transaction_shipping_details.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.user_id
     *
     * @return the value of order_transaction_shipping_details.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.user_id
     *
     * @param user_id the value for order_transaction_shipping_details.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.shop_id
     *
     * @return the value of order_transaction_shipping_details.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.shop_id
     *
     * @param shop_id the value for order_transaction_shipping_details.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.international_packaging_handling_costs
     *
     * @return the value of order_transaction_shipping_details.international_packaging_handling_costs
     *
     * @mbggenerated
     */
    public Double getInternational_packaging_handling_costs() {
        return international_packaging_handling_costs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.international_packaging_handling_costs
     *
     * @param international_packaging_handling_costs the value for order_transaction_shipping_details.international_packaging_handling_costs
     *
     * @mbggenerated
     */
    public void setInternational_packaging_handling_costs(Double international_packaging_handling_costs) {
        this.international_packaging_handling_costs = international_packaging_handling_costs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.international_packaging_handling_costs_currency_id
     *
     * @return the value of order_transaction_shipping_details.international_packaging_handling_costs_currency_id
     *
     * @mbggenerated
     */
    public String getInternational_packaging_handling_costs_currency_id() {
        return international_packaging_handling_costs_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.international_packaging_handling_costs_currency_id
     *
     * @param international_packaging_handling_costs_currency_id the value for order_transaction_shipping_details.international_packaging_handling_costs_currency_id
     *
     * @mbggenerated
     */
    public void setInternational_packaging_handling_costs_currency_id(String international_packaging_handling_costs_currency_id) {
        this.international_packaging_handling_costs_currency_id = international_packaging_handling_costs_currency_id == null ? null : international_packaging_handling_costs_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.originating_postal_code
     *
     * @return the value of order_transaction_shipping_details.originating_postal_code
     *
     * @mbggenerated
     */
    public String getOriginating_postal_code() {
        return originating_postal_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.originating_postal_code
     *
     * @param originating_postal_code the value for order_transaction_shipping_details.originating_postal_code
     *
     * @mbggenerated
     */
    public void setOriginating_postal_code(String originating_postal_code) {
        this.originating_postal_code = originating_postal_code == null ? null : originating_postal_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.packaging_handling_costs
     *
     * @return the value of order_transaction_shipping_details.packaging_handling_costs
     *
     * @mbggenerated
     */
    public Double getPackaging_handling_costs() {
        return packaging_handling_costs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.packaging_handling_costs
     *
     * @param packaging_handling_costs the value for order_transaction_shipping_details.packaging_handling_costs
     *
     * @mbggenerated
     */
    public void setPackaging_handling_costs(Double packaging_handling_costs) {
        this.packaging_handling_costs = packaging_handling_costs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.packaging_handling_costs_currency_id
     *
     * @return the value of order_transaction_shipping_details.packaging_handling_costs_currency_id
     *
     * @mbggenerated
     */
    public String getPackaging_handling_costs_currency_id() {
        return packaging_handling_costs_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.packaging_handling_costs_currency_id
     *
     * @param packaging_handling_costs_currency_id the value for order_transaction_shipping_details.packaging_handling_costs_currency_id
     *
     * @mbggenerated
     */
    public void setPackaging_handling_costs_currency_id(String packaging_handling_costs_currency_id) {
        this.packaging_handling_costs_currency_id = packaging_handling_costs_currency_id == null ? null : packaging_handling_costs_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.shipping_irregular
     *
     * @return the value of order_transaction_shipping_details.shipping_irregular
     *
     * @mbggenerated
     */
    public Boolean getShipping_irregular() {
        return shipping_irregular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.shipping_irregular
     *
     * @param shipping_irregular the value for order_transaction_shipping_details.shipping_irregular
     *
     * @mbggenerated
     */
    public void setShipping_irregular(Boolean shipping_irregular) {
        this.shipping_irregular = shipping_irregular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.COD_cost
     *
     * @return the value of order_transaction_shipping_details.COD_cost
     *
     * @mbggenerated
     */
    public Double getCOD_cost() {
        return COD_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.COD_cost
     *
     * @param COD_cost the value for order_transaction_shipping_details.COD_cost
     *
     * @mbggenerated
     */
    public void setCOD_cost(Double COD_cost) {
        this.COD_cost = COD_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.COD_cost_currency_id
     *
     * @return the value of order_transaction_shipping_details.COD_cost_currency_id
     *
     * @mbggenerated
     */
    public String getCOD_cost_currency_id() {
        return COD_cost_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.COD_cost_currency_id
     *
     * @param COD_cost_currency_id the value for order_transaction_shipping_details.COD_cost_currency_id
     *
     * @mbggenerated
     */
    public void setCOD_cost_currency_id(String COD_cost_currency_id) {
        this.COD_cost_currency_id = COD_cost_currency_id == null ? null : COD_cost_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.insurance_wanted
     *
     * @return the value of order_transaction_shipping_details.insurance_wanted
     *
     * @mbggenerated
     */
    public Boolean getInsurance_wanted() {
        return insurance_wanted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.insurance_wanted
     *
     * @param insurance_wanted the value for order_transaction_shipping_details.insurance_wanted
     *
     * @mbggenerated
     */
    public void setInsurance_wanted(Boolean insurance_wanted) {
        this.insurance_wanted = insurance_wanted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.sales_tax_amount
     *
     * @return the value of order_transaction_shipping_details.sales_tax_amount
     *
     * @mbggenerated
     */
    public Double getSales_tax_amount() {
        return sales_tax_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.sales_tax_amount
     *
     * @param sales_tax_amount the value for order_transaction_shipping_details.sales_tax_amount
     *
     * @mbggenerated
     */
    public void setSales_tax_amount(Double sales_tax_amount) {
        this.sales_tax_amount = sales_tax_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.sales_tax_amount_currency_id
     *
     * @return the value of order_transaction_shipping_details.sales_tax_amount_currency_id
     *
     * @mbggenerated
     */
    public String getSales_tax_amount_currency_id() {
        return sales_tax_amount_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.sales_tax_amount_currency_id
     *
     * @param sales_tax_amount_currency_id the value for order_transaction_shipping_details.sales_tax_amount_currency_id
     *
     * @mbggenerated
     */
    public void setSales_tax_amount_currency_id(String sales_tax_amount_currency_id) {
        this.sales_tax_amount_currency_id = sales_tax_amount_currency_id == null ? null : sales_tax_amount_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.sales_tax_percent
     *
     * @return the value of order_transaction_shipping_details.sales_tax_percent
     *
     * @mbggenerated
     */
    public Float getSales_tax_percent() {
        return sales_tax_percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.sales_tax_percent
     *
     * @param sales_tax_percent the value for order_transaction_shipping_details.sales_tax_percent
     *
     * @mbggenerated
     */
    public void setSales_tax_percent(Float sales_tax_percent) {
        this.sales_tax_percent = sales_tax_percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.sales_tax_state
     *
     * @return the value of order_transaction_shipping_details.sales_tax_state
     *
     * @mbggenerated
     */
    public String getSales_tax_state() {
        return sales_tax_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.sales_tax_state
     *
     * @param sales_tax_state the value for order_transaction_shipping_details.sales_tax_state
     *
     * @mbggenerated
     */
    public void setSales_tax_state(String sales_tax_state) {
        this.sales_tax_state = sales_tax_state == null ? null : sales_tax_state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.shipping_included_in_tax
     *
     * @return the value of order_transaction_shipping_details.shipping_included_in_tax
     *
     * @mbggenerated
     */
    public Boolean getShipping_included_in_tax() {
        return shipping_included_in_tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.shipping_included_in_tax
     *
     * @param shipping_included_in_tax the value for order_transaction_shipping_details.shipping_included_in_tax
     *
     * @mbggenerated
     */
    public void setShipping_included_in_tax(Boolean shipping_included_in_tax) {
        this.shipping_included_in_tax = shipping_included_in_tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.selling_manager_sales_record_number
     *
     * @return the value of order_transaction_shipping_details.selling_manager_sales_record_number
     *
     * @mbggenerated
     */
    public Integer getSelling_manager_sales_record_number() {
        return selling_manager_sales_record_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.selling_manager_sales_record_number
     *
     * @param selling_manager_sales_record_number the value for order_transaction_shipping_details.selling_manager_sales_record_number
     *
     * @mbggenerated
     */
    public void setSelling_manager_sales_record_number(Integer selling_manager_sales_record_number) {
        this.selling_manager_sales_record_number = selling_manager_sales_record_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_shipping_details.tax_jurisdiction
     *
     * @return the value of order_transaction_shipping_details.tax_jurisdiction
     *
     * @mbggenerated
     */
    public String getTax_jurisdiction() {
        return tax_jurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_shipping_details.tax_jurisdiction
     *
     * @param tax_jurisdiction the value for order_transaction_shipping_details.tax_jurisdiction
     *
     * @mbggenerated
     */
    public void setTax_jurisdiction(String tax_jurisdiction) {
        this.tax_jurisdiction = tax_jurisdiction == null ? null : tax_jurisdiction.trim();
    }
}