package yk.boxri.pojo;

import java.io.Serializable;
import java.util.Date;

public class OrderCancelDetails implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel_details.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel_details.order_cancel_details_id
     *
     * @mbggenerated
     */
    public Integer order_cancel_details_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel_details.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel_details.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel_details.cancel_complete_date
     *
     * @mbggenerated
     */
    public Date cancel_complete_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel_details.cancel_intiation_date
     *
     * @mbggenerated
     */
    public Date cancel_intiation_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel_details.cancel_intiator
     *
     * @mbggenerated
     */
    public String cancel_intiator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel_details.cancel_reason
     *
     * @mbggenerated
     */
    public String cancel_reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel_details.cancel_reason_details
     *
     * @mbggenerated
     */
    public String cancel_reason_details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_cancel_details
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel_details.order_id
     *
     * @return the value of order_cancel_details.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel_details.order_id
     *
     * @param order_id the value for order_cancel_details.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel_details.order_cancel_details_id
     *
     * @return the value of order_cancel_details.order_cancel_details_id
     *
     * @mbggenerated
     */
    public Integer getOrder_cancel_details_id() {
        return order_cancel_details_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel_details.order_cancel_details_id
     *
     * @param order_cancel_details_id the value for order_cancel_details.order_cancel_details_id
     *
     * @mbggenerated
     */
    public void setOrder_cancel_details_id(Integer order_cancel_details_id) {
        this.order_cancel_details_id = order_cancel_details_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel_details.user_id
     *
     * @return the value of order_cancel_details.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel_details.user_id
     *
     * @param user_id the value for order_cancel_details.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel_details.shop_id
     *
     * @return the value of order_cancel_details.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel_details.shop_id
     *
     * @param shop_id the value for order_cancel_details.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel_details.cancel_complete_date
     *
     * @return the value of order_cancel_details.cancel_complete_date
     *
     * @mbggenerated
     */
    public Date getCancel_complete_date() {
        return cancel_complete_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel_details.cancel_complete_date
     *
     * @param cancel_complete_date the value for order_cancel_details.cancel_complete_date
     *
     * @mbggenerated
     */
    public void setCancel_complete_date(Date cancel_complete_date) {
        this.cancel_complete_date = cancel_complete_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel_details.cancel_intiation_date
     *
     * @return the value of order_cancel_details.cancel_intiation_date
     *
     * @mbggenerated
     */
    public Date getCancel_intiation_date() {
        return cancel_intiation_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel_details.cancel_intiation_date
     *
     * @param cancel_intiation_date the value for order_cancel_details.cancel_intiation_date
     *
     * @mbggenerated
     */
    public void setCancel_intiation_date(Date cancel_intiation_date) {
        this.cancel_intiation_date = cancel_intiation_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel_details.cancel_intiator
     *
     * @return the value of order_cancel_details.cancel_intiator
     *
     * @mbggenerated
     */
    public String getCancel_intiator() {
        return cancel_intiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel_details.cancel_intiator
     *
     * @param cancel_intiator the value for order_cancel_details.cancel_intiator
     *
     * @mbggenerated
     */
    public void setCancel_intiator(String cancel_intiator) {
        this.cancel_intiator = cancel_intiator == null ? null : cancel_intiator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel_details.cancel_reason
     *
     * @return the value of order_cancel_details.cancel_reason
     *
     * @mbggenerated
     */
    public String getCancel_reason() {
        return cancel_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel_details.cancel_reason
     *
     * @param cancel_reason the value for order_cancel_details.cancel_reason
     *
     * @mbggenerated
     */
    public void setCancel_reason(String cancel_reason) {
        this.cancel_reason = cancel_reason == null ? null : cancel_reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel_details.cancel_reason_details
     *
     * @return the value of order_cancel_details.cancel_reason_details
     *
     * @mbggenerated
     */
    public String getCancel_reason_details() {
        return cancel_reason_details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel_details.cancel_reason_details
     *
     * @param cancel_reason_details the value for order_cancel_details.cancel_reason_details
     *
     * @mbggenerated
     */
    public void setCancel_reason_details(String cancel_reason_details) {
        this.cancel_reason_details = cancel_reason_details == null ? null : cancel_reason_details.trim();
    }
}