package yk.boxri.pojo;

import java.io.Serializable;

public class OrderShippingAddress implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.address_attribute_values
     *
     * @mbggenerated
     */
    public String address_attribute_values;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.address_id
     *
     * @mbggenerated
     */
    public String address_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.address_owner
     *
     * @mbggenerated
     */
    public String address_owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.address_usage
     *
     * @mbggenerated
     */
    public String address_usage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.city_name
     *
     * @mbggenerated
     */
    public String city_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.country
     *
     * @mbggenerated
     */
    public String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.country_name
     *
     * @mbggenerated
     */
    public String country_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.external_address_id
     *
     * @mbggenerated
     */
    public String external_address_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.name
     *
     * @mbggenerated
     */
    public String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.phone
     *
     * @mbggenerated
     */
    public String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.postal_code
     *
     * @mbggenerated
     */
    public String postal_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.state_or_province
     *
     * @mbggenerated
     */
    public String state_or_province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.Street1
     *
     * @mbggenerated
     */
    public String street1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_address.Street2
     *
     * @mbggenerated
     */
    public String street2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_shipping_address
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.order_id
     *
     * @return the value of order_shipping_address.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.order_id
     *
     * @param order_id the value for order_shipping_address.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.user_id
     *
     * @return the value of order_shipping_address.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.user_id
     *
     * @param user_id the value for order_shipping_address.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.shop_id
     *
     * @return the value of order_shipping_address.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.shop_id
     *
     * @param shop_id the value for order_shipping_address.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.address_attribute_values
     *
     * @return the value of order_shipping_address.address_attribute_values
     *
     * @mbggenerated
     */
    public String getAddress_attribute_values() {
        return address_attribute_values;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.address_attribute_values
     *
     * @param address_attribute_values the value for order_shipping_address.address_attribute_values
     *
     * @mbggenerated
     */
    public void setAddress_attribute_values(String address_attribute_values) {
        this.address_attribute_values = address_attribute_values == null ? null : address_attribute_values.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.address_id
     *
     * @return the value of order_shipping_address.address_id
     *
     * @mbggenerated
     */
    public String getAddress_id() {
        return address_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.address_id
     *
     * @param address_id the value for order_shipping_address.address_id
     *
     * @mbggenerated
     */
    public void setAddress_id(String address_id) {
        this.address_id = address_id == null ? null : address_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.address_owner
     *
     * @return the value of order_shipping_address.address_owner
     *
     * @mbggenerated
     */
    public String getAddress_owner() {
        return address_owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.address_owner
     *
     * @param address_owner the value for order_shipping_address.address_owner
     *
     * @mbggenerated
     */
    public void setAddress_owner(String address_owner) {
        this.address_owner = address_owner == null ? null : address_owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.address_usage
     *
     * @return the value of order_shipping_address.address_usage
     *
     * @mbggenerated
     */
    public String getAddress_usage() {
        return address_usage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.address_usage
     *
     * @param address_usage the value for order_shipping_address.address_usage
     *
     * @mbggenerated
     */
    public void setAddress_usage(String address_usage) {
        this.address_usage = address_usage == null ? null : address_usage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.city_name
     *
     * @return the value of order_shipping_address.city_name
     *
     * @mbggenerated
     */
    public String getCity_name() {
        return city_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.city_name
     *
     * @param city_name the value for order_shipping_address.city_name
     *
     * @mbggenerated
     */
    public void setCity_name(String city_name) {
        this.city_name = city_name == null ? null : city_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.country
     *
     * @return the value of order_shipping_address.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.country
     *
     * @param country the value for order_shipping_address.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.country_name
     *
     * @return the value of order_shipping_address.country_name
     *
     * @mbggenerated
     */
    public String getCountry_name() {
        return country_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.country_name
     *
     * @param country_name the value for order_shipping_address.country_name
     *
     * @mbggenerated
     */
    public void setCountry_name(String country_name) {
        this.country_name = country_name == null ? null : country_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.external_address_id
     *
     * @return the value of order_shipping_address.external_address_id
     *
     * @mbggenerated
     */
    public String getExternal_address_id() {
        return external_address_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.external_address_id
     *
     * @param external_address_id the value for order_shipping_address.external_address_id
     *
     * @mbggenerated
     */
    public void setExternal_address_id(String external_address_id) {
        this.external_address_id = external_address_id == null ? null : external_address_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.name
     *
     * @return the value of order_shipping_address.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.name
     *
     * @param name the value for order_shipping_address.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.phone
     *
     * @return the value of order_shipping_address.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.phone
     *
     * @param phone the value for order_shipping_address.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.postal_code
     *
     * @return the value of order_shipping_address.postal_code
     *
     * @mbggenerated
     */
    public String getPostal_code() {
        return postal_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.postal_code
     *
     * @param postal_code the value for order_shipping_address.postal_code
     *
     * @mbggenerated
     */
    public void setPostal_code(String postal_code) {
        this.postal_code = postal_code == null ? null : postal_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.state_or_province
     *
     * @return the value of order_shipping_address.state_or_province
     *
     * @mbggenerated
     */
    public String getState_or_province() {
        return state_or_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.state_or_province
     *
     * @param state_or_province the value for order_shipping_address.state_or_province
     *
     * @mbggenerated
     */
    public void setState_or_province(String state_or_province) {
        this.state_or_province = state_or_province == null ? null : state_or_province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.Street1
     *
     * @return the value of order_shipping_address.Street1
     *
     * @mbggenerated
     */
    public String getStreet1() {
        return street1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.Street1
     *
     * @param street1 the value for order_shipping_address.Street1
     *
     * @mbggenerated
     */
    public void setStreet1(String street1) {
        this.street1 = street1 == null ? null : street1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_address.Street2
     *
     * @return the value of order_shipping_address.Street2
     *
     * @mbggenerated
     */
    public String getStreet2() {
        return street2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_address.Street2
     *
     * @param street2 the value for order_shipping_address.Street2
     *
     * @mbggenerated
     */
    public void setStreet2(String street2) {
        this.street2 = street2 == null ? null : street2.trim();
    }
}