package yk.boxri.pojo;

import java.io.Serializable;

public class OrderTransactionVariation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_variation.transaction_id
     *
     * @mbggenerated
     */
    public String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_variation.transaction_variation_id
     *
     * @mbggenerated
     */
    public Integer transaction_variation_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_variation.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_variation.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_variation.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_variation.SKU
     *
     * @mbggenerated
     */
    public String SKU;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_variation.variation_specifics
     *
     * @mbggenerated
     */
    public String variation_specifics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_variation.variation_title
     *
     * @mbggenerated
     */
    public String variation_title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_variation.variation_view_item_URL
     *
     * @mbggenerated
     */
    public String variation_view_item_URL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_transaction_variation
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_variation.transaction_id
     *
     * @return the value of order_transaction_variation.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_variation.transaction_id
     *
     * @param transaction_id the value for order_transaction_variation.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_variation.transaction_variation_id
     *
     * @return the value of order_transaction_variation.transaction_variation_id
     *
     * @mbggenerated
     */
    public Integer getTransaction_variation_id() {
        return transaction_variation_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_variation.transaction_variation_id
     *
     * @param transaction_variation_id the value for order_transaction_variation.transaction_variation_id
     *
     * @mbggenerated
     */
    public void setTransaction_variation_id(Integer transaction_variation_id) {
        this.transaction_variation_id = transaction_variation_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_variation.order_id
     *
     * @return the value of order_transaction_variation.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_variation.order_id
     *
     * @param order_id the value for order_transaction_variation.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_variation.user_id
     *
     * @return the value of order_transaction_variation.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_variation.user_id
     *
     * @param user_id the value for order_transaction_variation.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_variation.shop_id
     *
     * @return the value of order_transaction_variation.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_variation.shop_id
     *
     * @param shop_id the value for order_transaction_variation.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_variation.SKU
     *
     * @return the value of order_transaction_variation.SKU
     *
     * @mbggenerated
     */
    public String getSKU() {
        return SKU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_variation.SKU
     *
     * @param SKU the value for order_transaction_variation.SKU
     *
     * @mbggenerated
     */
    public void setSKU(String SKU) {
        this.SKU = SKU == null ? null : SKU.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_variation.variation_specifics
     *
     * @return the value of order_transaction_variation.variation_specifics
     *
     * @mbggenerated
     */
    public String getVariation_specifics() {
        return variation_specifics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_variation.variation_specifics
     *
     * @param variation_specifics the value for order_transaction_variation.variation_specifics
     *
     * @mbggenerated
     */
    public void setVariation_specifics(String variation_specifics) {
        this.variation_specifics = variation_specifics == null ? null : variation_specifics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_variation.variation_title
     *
     * @return the value of order_transaction_variation.variation_title
     *
     * @mbggenerated
     */
    public String getVariation_title() {
        return variation_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_variation.variation_title
     *
     * @param variation_title the value for order_transaction_variation.variation_title
     *
     * @mbggenerated
     */
    public void setVariation_title(String variation_title) {
        this.variation_title = variation_title == null ? null : variation_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_variation.variation_view_item_URL
     *
     * @return the value of order_transaction_variation.variation_view_item_URL
     *
     * @mbggenerated
     */
    public String getVariation_view_item_URL() {
        return variation_view_item_URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_variation.variation_view_item_URL
     *
     * @param variation_view_item_URL the value for order_transaction_variation.variation_view_item_URL
     *
     * @mbggenerated
     */
    public void setVariation_view_item_URL(String variation_view_item_URL) {
        this.variation_view_item_URL = variation_view_item_URL == null ? null : variation_view_item_URL.trim();
    }
}