package yk.boxri.pojo;

import java.io.Serializable;
import java.util.Date;

public class OrderInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.buyer_user_id
     *
     * @mbggenerated
     */
    public String buyer_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_status
     *
     * @mbggenerated
     */
    public String order_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.paid_time
     *
     * @mbggenerated
     */
    public Date paid_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.payment_hold_status
     *
     * @mbggenerated
     */
    public String payment_hold_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.payment_methods
     *
     * @mbggenerated
     */
    public String payment_methods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.buyer_tax_identifier
     *
     * @mbggenerated
     */
    public String buyer_tax_identifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.buyer_package_enclosures
     *
     * @mbggenerated
     */
    public String buyer_package_enclosures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.createing_time
     *
     * @mbggenerated
     */
    public Date createing_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.extended_order_id
     *
     * @mbggenerated
     */
    public String extended_order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.creating_user_role
     *
     * @mbggenerated
     */
    public String creating_user_role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.checkout_status_ebay_payment_status
     *
     * @mbggenerated
     */
    public String checkout_status_ebay_payment_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.checkout_status_integrated_merchant_credit_card_enabled
     *
     * @mbggenerated
     */
    public Boolean checkout_status_integrated_merchant_credit_card_enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.checkout_status_last_modified_time
     *
     * @mbggenerated
     */
    public Date checkout_status_last_modified_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.checkout_status_payment_instrument
     *
     * @mbggenerated
     */
    public String checkout_status_payment_instrument;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.checkout_status_payment_methods
     *
     * @mbggenerated
     */
    public String checkout_status_payment_methods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.checkout_status_status
     *
     * @mbggenerated
     */
    public String checkout_status_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pickup_method_selected_merchant_pickup_code
     *
     * @mbggenerated
     */
    public String pickup_method_selected_merchant_pickup_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pickup_method_selected_pickup_fulfillment_time
     *
     * @mbggenerated
     */
    public Date pickup_method_selected_pickup_fulfillment_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pickup_method_selected_pickup_location_UUID
     *
     * @mbggenerated
     */
    public String pickup_method_selected_pickup_location_UUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pickup_method_selected_pickup_method
     *
     * @mbggenerated
     */
    public String pickup_method_selected_pickup_method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pickup_method_selected_pickup_status
     *
     * @mbggenerated
     */
    public String pickup_method_selected_pickup_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pickup_method_selected_pickup_store_id
     *
     * @mbggenerated
     */
    public String pickup_method_selected_pickup_store_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.seller_email
     *
     * @mbggenerated
     */
    public String seller_email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.seller_user_id
     *
     * @mbggenerated
     */
    public String seller_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.shipped_time
     *
     * @mbggenerated
     */
    public Date shipped_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.subtotal
     *
     * @mbggenerated
     */
    public Double subtotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.subtoal_currency_id
     *
     * @mbggenerated
     */
    public String subtoal_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.total
     *
     * @mbggenerated
     */
    public Double total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.total_currency_id
     *
     * @mbggenerated
     */
    public String total_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.EIAS_token
     *
     * @mbggenerated
     */
    public String EIAS_token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_seller_EIAS_token
     *
     * @mbggenerated
     */
    public String order_seller_EIAS_token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.shipping_convenience_charge
     *
     * @mbggenerated
     */
    public Double shipping_convenience_charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.shipping_convenience_charge_currency_id
     *
     * @mbggenerated
     */
    public String shipping_convenience_charge_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.is_multiLeg_shipping
     *
     * @mbggenerated
     */
    public Boolean is_multiLeg_shipping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.logistics_plan_type
     *
     * @mbggenerated
     */
    public String logistics_plan_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.integrated_merchant_credit_card_enabled
     *
     * @mbggenerated
     */
    public Boolean integrated_merchant_credit_card_enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.adjustment_amount
     *
     * @mbggenerated
     */
    public Double adjustment_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.adjustment_amount_currency_id
     *
     * @mbggenerated
     */
    public String adjustment_amount_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.amount_paid
     *
     * @mbggenerated
     */
    public Double amount_paid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.amount_paid_currency_id
     *
     * @mbggenerated
     */
    public String amount_paid_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.amount_saved
     *
     * @mbggenerated
     */
    public Double amount_saved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.amount_saved_currency_id
     *
     * @mbggenerated
     */
    public String amount_saved_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.buyer_checkout_message
     *
     * @mbggenerated
     */
    public String buyer_checkout_message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.cancel_status
     *
     * @mbggenerated
     */
    public String cancel_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.cancel_reason
     *
     * @mbggenerated
     */
    public String cancel_reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.cancal_reason_details
     *
     * @mbggenerated
     */
    public String cancal_reason_details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.containseBay_plus_transaction
     *
     * @mbggenerated
     */
    public Boolean containseBay_plus_transaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_info
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param order_id the value for order_info.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_id
     *
     * @return the value of order_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_id
     *
     * @param user_id the value for order_info.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.shop_id
     *
     * @return the value of order_info.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.shop_id
     *
     * @param shop_id the value for order_info.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.buyer_user_id
     *
     * @return the value of order_info.buyer_user_id
     *
     * @mbggenerated
     */
    public String getBuyer_user_id() {
        return buyer_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.buyer_user_id
     *
     * @param buyer_user_id the value for order_info.buyer_user_id
     *
     * @mbggenerated
     */
    public void setBuyer_user_id(String buyer_user_id) {
        this.buyer_user_id = buyer_user_id == null ? null : buyer_user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_status
     *
     * @return the value of order_info.order_status
     *
     * @mbggenerated
     */
    public String getOrder_status() {
        return order_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_status
     *
     * @param order_status the value for order_info.order_status
     *
     * @mbggenerated
     */
    public void setOrder_status(String order_status) {
        this.order_status = order_status == null ? null : order_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.paid_time
     *
     * @return the value of order_info.paid_time
     *
     * @mbggenerated
     */
    public Date getPaid_time() {
        return paid_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.paid_time
     *
     * @param paid_time the value for order_info.paid_time
     *
     * @mbggenerated
     */
    public void setPaid_time(Date paid_time) {
        this.paid_time = paid_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.payment_hold_status
     *
     * @return the value of order_info.payment_hold_status
     *
     * @mbggenerated
     */
    public String getPayment_hold_status() {
        return payment_hold_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.payment_hold_status
     *
     * @param payment_hold_status the value for order_info.payment_hold_status
     *
     * @mbggenerated
     */
    public void setPayment_hold_status(String payment_hold_status) {
        this.payment_hold_status = payment_hold_status == null ? null : payment_hold_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.payment_methods
     *
     * @return the value of order_info.payment_methods
     *
     * @mbggenerated
     */
    public String getPayment_methods() {
        return payment_methods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.payment_methods
     *
     * @param payment_methods the value for order_info.payment_methods
     *
     * @mbggenerated
     */
    public void setPayment_methods(String payment_methods) {
        this.payment_methods = payment_methods == null ? null : payment_methods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.buyer_tax_identifier
     *
     * @return the value of order_info.buyer_tax_identifier
     *
     * @mbggenerated
     */
    public String getBuyer_tax_identifier() {
        return buyer_tax_identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.buyer_tax_identifier
     *
     * @param buyer_tax_identifier the value for order_info.buyer_tax_identifier
     *
     * @mbggenerated
     */
    public void setBuyer_tax_identifier(String buyer_tax_identifier) {
        this.buyer_tax_identifier = buyer_tax_identifier == null ? null : buyer_tax_identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.buyer_package_enclosures
     *
     * @return the value of order_info.buyer_package_enclosures
     *
     * @mbggenerated
     */
    public String getBuyer_package_enclosures() {
        return buyer_package_enclosures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.buyer_package_enclosures
     *
     * @param buyer_package_enclosures the value for order_info.buyer_package_enclosures
     *
     * @mbggenerated
     */
    public void setBuyer_package_enclosures(String buyer_package_enclosures) {
        this.buyer_package_enclosures = buyer_package_enclosures == null ? null : buyer_package_enclosures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.createing_time
     *
     * @return the value of order_info.createing_time
     *
     * @mbggenerated
     */
    public Date getCreateing_time() {
        return createing_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.createing_time
     *
     * @param createing_time the value for order_info.createing_time
     *
     * @mbggenerated
     */
    public void setCreateing_time(Date createing_time) {
        this.createing_time = createing_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.extended_order_id
     *
     * @return the value of order_info.extended_order_id
     *
     * @mbggenerated
     */
    public String getExtended_order_id() {
        return extended_order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.extended_order_id
     *
     * @param extended_order_id the value for order_info.extended_order_id
     *
     * @mbggenerated
     */
    public void setExtended_order_id(String extended_order_id) {
        this.extended_order_id = extended_order_id == null ? null : extended_order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.creating_user_role
     *
     * @return the value of order_info.creating_user_role
     *
     * @mbggenerated
     */
    public String getCreating_user_role() {
        return creating_user_role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.creating_user_role
     *
     * @param creating_user_role the value for order_info.creating_user_role
     *
     * @mbggenerated
     */
    public void setCreating_user_role(String creating_user_role) {
        this.creating_user_role = creating_user_role == null ? null : creating_user_role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.checkout_status_ebay_payment_status
     *
     * @return the value of order_info.checkout_status_ebay_payment_status
     *
     * @mbggenerated
     */
    public String getCheckout_status_ebay_payment_status() {
        return checkout_status_ebay_payment_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.checkout_status_ebay_payment_status
     *
     * @param checkout_status_ebay_payment_status the value for order_info.checkout_status_ebay_payment_status
     *
     * @mbggenerated
     */
    public void setCheckout_status_ebay_payment_status(String checkout_status_ebay_payment_status) {
        this.checkout_status_ebay_payment_status = checkout_status_ebay_payment_status == null ? null : checkout_status_ebay_payment_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.checkout_status_integrated_merchant_credit_card_enabled
     *
     * @return the value of order_info.checkout_status_integrated_merchant_credit_card_enabled
     *
     * @mbggenerated
     */
    public Boolean getCheckout_status_integrated_merchant_credit_card_enabled() {
        return checkout_status_integrated_merchant_credit_card_enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.checkout_status_integrated_merchant_credit_card_enabled
     *
     * @param checkout_status_integrated_merchant_credit_card_enabled the value for order_info.checkout_status_integrated_merchant_credit_card_enabled
     *
     * @mbggenerated
     */
    public void setCheckout_status_integrated_merchant_credit_card_enabled(Boolean checkout_status_integrated_merchant_credit_card_enabled) {
        this.checkout_status_integrated_merchant_credit_card_enabled = checkout_status_integrated_merchant_credit_card_enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.checkout_status_last_modified_time
     *
     * @return the value of order_info.checkout_status_last_modified_time
     *
     * @mbggenerated
     */
    public Date getCheckout_status_last_modified_time() {
        return checkout_status_last_modified_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.checkout_status_last_modified_time
     *
     * @param checkout_status_last_modified_time the value for order_info.checkout_status_last_modified_time
     *
     * @mbggenerated
     */
    public void setCheckout_status_last_modified_time(Date checkout_status_last_modified_time) {
        this.checkout_status_last_modified_time = checkout_status_last_modified_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.checkout_status_payment_instrument
     *
     * @return the value of order_info.checkout_status_payment_instrument
     *
     * @mbggenerated
     */
    public String getCheckout_status_payment_instrument() {
        return checkout_status_payment_instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.checkout_status_payment_instrument
     *
     * @param checkout_status_payment_instrument the value for order_info.checkout_status_payment_instrument
     *
     * @mbggenerated
     */
    public void setCheckout_status_payment_instrument(String checkout_status_payment_instrument) {
        this.checkout_status_payment_instrument = checkout_status_payment_instrument == null ? null : checkout_status_payment_instrument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.checkout_status_payment_methods
     *
     * @return the value of order_info.checkout_status_payment_methods
     *
     * @mbggenerated
     */
    public String getCheckout_status_payment_methods() {
        return checkout_status_payment_methods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.checkout_status_payment_methods
     *
     * @param checkout_status_payment_methods the value for order_info.checkout_status_payment_methods
     *
     * @mbggenerated
     */
    public void setCheckout_status_payment_methods(String checkout_status_payment_methods) {
        this.checkout_status_payment_methods = checkout_status_payment_methods == null ? null : checkout_status_payment_methods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.checkout_status_status
     *
     * @return the value of order_info.checkout_status_status
     *
     * @mbggenerated
     */
    public String getCheckout_status_status() {
        return checkout_status_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.checkout_status_status
     *
     * @param checkout_status_status the value for order_info.checkout_status_status
     *
     * @mbggenerated
     */
    public void setCheckout_status_status(String checkout_status_status) {
        this.checkout_status_status = checkout_status_status == null ? null : checkout_status_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pickup_method_selected_merchant_pickup_code
     *
     * @return the value of order_info.pickup_method_selected_merchant_pickup_code
     *
     * @mbggenerated
     */
    public String getPickup_method_selected_merchant_pickup_code() {
        return pickup_method_selected_merchant_pickup_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pickup_method_selected_merchant_pickup_code
     *
     * @param pickup_method_selected_merchant_pickup_code the value for order_info.pickup_method_selected_merchant_pickup_code
     *
     * @mbggenerated
     */
    public void setPickup_method_selected_merchant_pickup_code(String pickup_method_selected_merchant_pickup_code) {
        this.pickup_method_selected_merchant_pickup_code = pickup_method_selected_merchant_pickup_code == null ? null : pickup_method_selected_merchant_pickup_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pickup_method_selected_pickup_fulfillment_time
     *
     * @return the value of order_info.pickup_method_selected_pickup_fulfillment_time
     *
     * @mbggenerated
     */
    public Date getPickup_method_selected_pickup_fulfillment_time() {
        return pickup_method_selected_pickup_fulfillment_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pickup_method_selected_pickup_fulfillment_time
     *
     * @param pickup_method_selected_pickup_fulfillment_time the value for order_info.pickup_method_selected_pickup_fulfillment_time
     *
     * @mbggenerated
     */
    public void setPickup_method_selected_pickup_fulfillment_time(Date pickup_method_selected_pickup_fulfillment_time) {
        this.pickup_method_selected_pickup_fulfillment_time = pickup_method_selected_pickup_fulfillment_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pickup_method_selected_pickup_location_UUID
     *
     * @return the value of order_info.pickup_method_selected_pickup_location_UUID
     *
     * @mbggenerated
     */
    public String getPickup_method_selected_pickup_location_UUID() {
        return pickup_method_selected_pickup_location_UUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pickup_method_selected_pickup_location_UUID
     *
     * @param pickup_method_selected_pickup_location_UUID the value for order_info.pickup_method_selected_pickup_location_UUID
     *
     * @mbggenerated
     */
    public void setPickup_method_selected_pickup_location_UUID(String pickup_method_selected_pickup_location_UUID) {
        this.pickup_method_selected_pickup_location_UUID = pickup_method_selected_pickup_location_UUID == null ? null : pickup_method_selected_pickup_location_UUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pickup_method_selected_pickup_method
     *
     * @return the value of order_info.pickup_method_selected_pickup_method
     *
     * @mbggenerated
     */
    public String getPickup_method_selected_pickup_method() {
        return pickup_method_selected_pickup_method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pickup_method_selected_pickup_method
     *
     * @param pickup_method_selected_pickup_method the value for order_info.pickup_method_selected_pickup_method
     *
     * @mbggenerated
     */
    public void setPickup_method_selected_pickup_method(String pickup_method_selected_pickup_method) {
        this.pickup_method_selected_pickup_method = pickup_method_selected_pickup_method == null ? null : pickup_method_selected_pickup_method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pickup_method_selected_pickup_status
     *
     * @return the value of order_info.pickup_method_selected_pickup_status
     *
     * @mbggenerated
     */
    public String getPickup_method_selected_pickup_status() {
        return pickup_method_selected_pickup_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pickup_method_selected_pickup_status
     *
     * @param pickup_method_selected_pickup_status the value for order_info.pickup_method_selected_pickup_status
     *
     * @mbggenerated
     */
    public void setPickup_method_selected_pickup_status(String pickup_method_selected_pickup_status) {
        this.pickup_method_selected_pickup_status = pickup_method_selected_pickup_status == null ? null : pickup_method_selected_pickup_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pickup_method_selected_pickup_store_id
     *
     * @return the value of order_info.pickup_method_selected_pickup_store_id
     *
     * @mbggenerated
     */
    public String getPickup_method_selected_pickup_store_id() {
        return pickup_method_selected_pickup_store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pickup_method_selected_pickup_store_id
     *
     * @param pickup_method_selected_pickup_store_id the value for order_info.pickup_method_selected_pickup_store_id
     *
     * @mbggenerated
     */
    public void setPickup_method_selected_pickup_store_id(String pickup_method_selected_pickup_store_id) {
        this.pickup_method_selected_pickup_store_id = pickup_method_selected_pickup_store_id == null ? null : pickup_method_selected_pickup_store_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.seller_email
     *
     * @return the value of order_info.seller_email
     *
     * @mbggenerated
     */
    public String getSeller_email() {
        return seller_email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.seller_email
     *
     * @param seller_email the value for order_info.seller_email
     *
     * @mbggenerated
     */
    public void setSeller_email(String seller_email) {
        this.seller_email = seller_email == null ? null : seller_email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.seller_user_id
     *
     * @return the value of order_info.seller_user_id
     *
     * @mbggenerated
     */
    public String getSeller_user_id() {
        return seller_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.seller_user_id
     *
     * @param seller_user_id the value for order_info.seller_user_id
     *
     * @mbggenerated
     */
    public void setSeller_user_id(String seller_user_id) {
        this.seller_user_id = seller_user_id == null ? null : seller_user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.shipped_time
     *
     * @return the value of order_info.shipped_time
     *
     * @mbggenerated
     */
    public Date getShipped_time() {
        return shipped_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.shipped_time
     *
     * @param shipped_time the value for order_info.shipped_time
     *
     * @mbggenerated
     */
    public void setShipped_time(Date shipped_time) {
        this.shipped_time = shipped_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.subtotal
     *
     * @return the value of order_info.subtotal
     *
     * @mbggenerated
     */
    public Double getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.subtotal
     *
     * @param subtotal the value for order_info.subtotal
     *
     * @mbggenerated
     */
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.subtoal_currency_id
     *
     * @return the value of order_info.subtoal_currency_id
     *
     * @mbggenerated
     */
    public String getSubtoal_currency_id() {
        return subtoal_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.subtoal_currency_id
     *
     * @param subtoal_currency_id the value for order_info.subtoal_currency_id
     *
     * @mbggenerated
     */
    public void setSubtoal_currency_id(String subtoal_currency_id) {
        this.subtoal_currency_id = subtoal_currency_id == null ? null : subtoal_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.total
     *
     * @return the value of order_info.total
     *
     * @mbggenerated
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.total
     *
     * @param total the value for order_info.total
     *
     * @mbggenerated
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.total_currency_id
     *
     * @return the value of order_info.total_currency_id
     *
     * @mbggenerated
     */
    public String getTotal_currency_id() {
        return total_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.total_currency_id
     *
     * @param total_currency_id the value for order_info.total_currency_id
     *
     * @mbggenerated
     */
    public void setTotal_currency_id(String total_currency_id) {
        this.total_currency_id = total_currency_id == null ? null : total_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.EIAS_token
     *
     * @return the value of order_info.EIAS_token
     *
     * @mbggenerated
     */
    public String getEIAS_token() {
        return EIAS_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.EIAS_token
     *
     * @param EIAS_token the value for order_info.EIAS_token
     *
     * @mbggenerated
     */
    public void setEIAS_token(String EIAS_token) {
        this.EIAS_token = EIAS_token == null ? null : EIAS_token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_seller_EIAS_token
     *
     * @return the value of order_info.order_seller_EIAS_token
     *
     * @mbggenerated
     */
    public String getOrder_seller_EIAS_token() {
        return order_seller_EIAS_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_seller_EIAS_token
     *
     * @param order_seller_EIAS_token the value for order_info.order_seller_EIAS_token
     *
     * @mbggenerated
     */
    public void setOrder_seller_EIAS_token(String order_seller_EIAS_token) {
        this.order_seller_EIAS_token = order_seller_EIAS_token == null ? null : order_seller_EIAS_token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.shipping_convenience_charge
     *
     * @return the value of order_info.shipping_convenience_charge
     *
     * @mbggenerated
     */
    public Double getShipping_convenience_charge() {
        return shipping_convenience_charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.shipping_convenience_charge
     *
     * @param shipping_convenience_charge the value for order_info.shipping_convenience_charge
     *
     * @mbggenerated
     */
    public void setShipping_convenience_charge(Double shipping_convenience_charge) {
        this.shipping_convenience_charge = shipping_convenience_charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.shipping_convenience_charge_currency_id
     *
     * @return the value of order_info.shipping_convenience_charge_currency_id
     *
     * @mbggenerated
     */
    public String getShipping_convenience_charge_currency_id() {
        return shipping_convenience_charge_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.shipping_convenience_charge_currency_id
     *
     * @param shipping_convenience_charge_currency_id the value for order_info.shipping_convenience_charge_currency_id
     *
     * @mbggenerated
     */
    public void setShipping_convenience_charge_currency_id(String shipping_convenience_charge_currency_id) {
        this.shipping_convenience_charge_currency_id = shipping_convenience_charge_currency_id == null ? null : shipping_convenience_charge_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.is_multiLeg_shipping
     *
     * @return the value of order_info.is_multiLeg_shipping
     *
     * @mbggenerated
     */
    public Boolean getIs_multiLeg_shipping() {
        return is_multiLeg_shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.is_multiLeg_shipping
     *
     * @param is_multiLeg_shipping the value for order_info.is_multiLeg_shipping
     *
     * @mbggenerated
     */
    public void setIs_multiLeg_shipping(Boolean is_multiLeg_shipping) {
        this.is_multiLeg_shipping = is_multiLeg_shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.logistics_plan_type
     *
     * @return the value of order_info.logistics_plan_type
     *
     * @mbggenerated
     */
    public String getLogistics_plan_type() {
        return logistics_plan_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.logistics_plan_type
     *
     * @param logistics_plan_type the value for order_info.logistics_plan_type
     *
     * @mbggenerated
     */
    public void setLogistics_plan_type(String logistics_plan_type) {
        this.logistics_plan_type = logistics_plan_type == null ? null : logistics_plan_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.integrated_merchant_credit_card_enabled
     *
     * @return the value of order_info.integrated_merchant_credit_card_enabled
     *
     * @mbggenerated
     */
    public Boolean getIntegrated_merchant_credit_card_enabled() {
        return integrated_merchant_credit_card_enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.integrated_merchant_credit_card_enabled
     *
     * @param integrated_merchant_credit_card_enabled the value for order_info.integrated_merchant_credit_card_enabled
     *
     * @mbggenerated
     */
    public void setIntegrated_merchant_credit_card_enabled(Boolean integrated_merchant_credit_card_enabled) {
        this.integrated_merchant_credit_card_enabled = integrated_merchant_credit_card_enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.adjustment_amount
     *
     * @return the value of order_info.adjustment_amount
     *
     * @mbggenerated
     */
    public Double getAdjustment_amount() {
        return adjustment_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.adjustment_amount
     *
     * @param adjustment_amount the value for order_info.adjustment_amount
     *
     * @mbggenerated
     */
    public void setAdjustment_amount(Double adjustment_amount) {
        this.adjustment_amount = adjustment_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.adjustment_amount_currency_id
     *
     * @return the value of order_info.adjustment_amount_currency_id
     *
     * @mbggenerated
     */
    public String getAdjustment_amount_currency_id() {
        return adjustment_amount_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.adjustment_amount_currency_id
     *
     * @param adjustment_amount_currency_id the value for order_info.adjustment_amount_currency_id
     *
     * @mbggenerated
     */
    public void setAdjustment_amount_currency_id(String adjustment_amount_currency_id) {
        this.adjustment_amount_currency_id = adjustment_amount_currency_id == null ? null : adjustment_amount_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.amount_paid
     *
     * @return the value of order_info.amount_paid
     *
     * @mbggenerated
     */
    public Double getAmount_paid() {
        return amount_paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.amount_paid
     *
     * @param amount_paid the value for order_info.amount_paid
     *
     * @mbggenerated
     */
    public void setAmount_paid(Double amount_paid) {
        this.amount_paid = amount_paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.amount_paid_currency_id
     *
     * @return the value of order_info.amount_paid_currency_id
     *
     * @mbggenerated
     */
    public String getAmount_paid_currency_id() {
        return amount_paid_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.amount_paid_currency_id
     *
     * @param amount_paid_currency_id the value for order_info.amount_paid_currency_id
     *
     * @mbggenerated
     */
    public void setAmount_paid_currency_id(String amount_paid_currency_id) {
        this.amount_paid_currency_id = amount_paid_currency_id == null ? null : amount_paid_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.amount_saved
     *
     * @return the value of order_info.amount_saved
     *
     * @mbggenerated
     */
    public Double getAmount_saved() {
        return amount_saved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.amount_saved
     *
     * @param amount_saved the value for order_info.amount_saved
     *
     * @mbggenerated
     */
    public void setAmount_saved(Double amount_saved) {
        this.amount_saved = amount_saved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.amount_saved_currency_id
     *
     * @return the value of order_info.amount_saved_currency_id
     *
     * @mbggenerated
     */
    public String getAmount_saved_currency_id() {
        return amount_saved_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.amount_saved_currency_id
     *
     * @param amount_saved_currency_id the value for order_info.amount_saved_currency_id
     *
     * @mbggenerated
     */
    public void setAmount_saved_currency_id(String amount_saved_currency_id) {
        this.amount_saved_currency_id = amount_saved_currency_id == null ? null : amount_saved_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.buyer_checkout_message
     *
     * @return the value of order_info.buyer_checkout_message
     *
     * @mbggenerated
     */
    public String getBuyer_checkout_message() {
        return buyer_checkout_message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.buyer_checkout_message
     *
     * @param buyer_checkout_message the value for order_info.buyer_checkout_message
     *
     * @mbggenerated
     */
    public void setBuyer_checkout_message(String buyer_checkout_message) {
        this.buyer_checkout_message = buyer_checkout_message == null ? null : buyer_checkout_message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.cancel_status
     *
     * @return the value of order_info.cancel_status
     *
     * @mbggenerated
     */
    public String getCancel_status() {
        return cancel_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.cancel_status
     *
     * @param cancel_status the value for order_info.cancel_status
     *
     * @mbggenerated
     */
    public void setCancel_status(String cancel_status) {
        this.cancel_status = cancel_status == null ? null : cancel_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.cancel_reason
     *
     * @return the value of order_info.cancel_reason
     *
     * @mbggenerated
     */
    public String getCancel_reason() {
        return cancel_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.cancel_reason
     *
     * @param cancel_reason the value for order_info.cancel_reason
     *
     * @mbggenerated
     */
    public void setCancel_reason(String cancel_reason) {
        this.cancel_reason = cancel_reason == null ? null : cancel_reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.cancal_reason_details
     *
     * @return the value of order_info.cancal_reason_details
     *
     * @mbggenerated
     */
    public String getCancal_reason_details() {
        return cancal_reason_details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.cancal_reason_details
     *
     * @param cancal_reason_details the value for order_info.cancal_reason_details
     *
     * @mbggenerated
     */
    public void setCancal_reason_details(String cancal_reason_details) {
        this.cancal_reason_details = cancal_reason_details == null ? null : cancal_reason_details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.containseBay_plus_transaction
     *
     * @return the value of order_info.containseBay_plus_transaction
     *
     * @mbggenerated
     */
    public Boolean getContainseBay_plus_transaction() {
        return containseBay_plus_transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.containseBay_plus_transaction
     *
     * @param containseBay_plus_transaction the value for order_info.containseBay_plus_transaction
     *
     * @mbggenerated
     */
    public void setContainseBay_plus_transaction(Boolean containseBay_plus_transaction) {
        this.containseBay_plus_transaction = containseBay_plus_transaction;
    }
}