package yk.boxri.pojo;

import java.io.Serializable;

public class OrderTransactionDigitalDeliverySelected implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_digital_delivery_selected.transaction_id
     *
     * @mbggenerated
     */
    public String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_digital_delivery_selected.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_digital_delivery_selected.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_digital_delivery_selected.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_digital_delivery_selected.recipient_email
     *
     * @mbggenerated
     */
    public String recipient_email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_digital_delivery_selected.recipient_name
     *
     * @mbggenerated
     */
    public String recipient_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_digital_delivery_selected.sender_email
     *
     * @mbggenerated
     */
    public String sender_email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_digital_delivery_selected.sender_name
     *
     * @mbggenerated
     */
    public String sender_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_digital_delivery_selected.delivery_method
     *
     * @mbggenerated
     */
    public String delivery_method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_digital_delivery_selected.delivery_status_email
     *
     * @mbggenerated
     */
    public String delivery_status_email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_transaction_digital_delivery_selected
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_digital_delivery_selected.transaction_id
     *
     * @return the value of order_transaction_digital_delivery_selected.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_digital_delivery_selected.transaction_id
     *
     * @param transaction_id the value for order_transaction_digital_delivery_selected.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_digital_delivery_selected.order_id
     *
     * @return the value of order_transaction_digital_delivery_selected.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_digital_delivery_selected.order_id
     *
     * @param order_id the value for order_transaction_digital_delivery_selected.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_digital_delivery_selected.user_id
     *
     * @return the value of order_transaction_digital_delivery_selected.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_digital_delivery_selected.user_id
     *
     * @param user_id the value for order_transaction_digital_delivery_selected.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_digital_delivery_selected.shop_id
     *
     * @return the value of order_transaction_digital_delivery_selected.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_digital_delivery_selected.shop_id
     *
     * @param shop_id the value for order_transaction_digital_delivery_selected.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_digital_delivery_selected.recipient_email
     *
     * @return the value of order_transaction_digital_delivery_selected.recipient_email
     *
     * @mbggenerated
     */
    public String getRecipient_email() {
        return recipient_email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_digital_delivery_selected.recipient_email
     *
     * @param recipient_email the value for order_transaction_digital_delivery_selected.recipient_email
     *
     * @mbggenerated
     */
    public void setRecipient_email(String recipient_email) {
        this.recipient_email = recipient_email == null ? null : recipient_email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_digital_delivery_selected.recipient_name
     *
     * @return the value of order_transaction_digital_delivery_selected.recipient_name
     *
     * @mbggenerated
     */
    public String getRecipient_name() {
        return recipient_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_digital_delivery_selected.recipient_name
     *
     * @param recipient_name the value for order_transaction_digital_delivery_selected.recipient_name
     *
     * @mbggenerated
     */
    public void setRecipient_name(String recipient_name) {
        this.recipient_name = recipient_name == null ? null : recipient_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_digital_delivery_selected.sender_email
     *
     * @return the value of order_transaction_digital_delivery_selected.sender_email
     *
     * @mbggenerated
     */
    public String getSender_email() {
        return sender_email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_digital_delivery_selected.sender_email
     *
     * @param sender_email the value for order_transaction_digital_delivery_selected.sender_email
     *
     * @mbggenerated
     */
    public void setSender_email(String sender_email) {
        this.sender_email = sender_email == null ? null : sender_email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_digital_delivery_selected.sender_name
     *
     * @return the value of order_transaction_digital_delivery_selected.sender_name
     *
     * @mbggenerated
     */
    public String getSender_name() {
        return sender_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_digital_delivery_selected.sender_name
     *
     * @param sender_name the value for order_transaction_digital_delivery_selected.sender_name
     *
     * @mbggenerated
     */
    public void setSender_name(String sender_name) {
        this.sender_name = sender_name == null ? null : sender_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_digital_delivery_selected.delivery_method
     *
     * @return the value of order_transaction_digital_delivery_selected.delivery_method
     *
     * @mbggenerated
     */
    public String getDelivery_method() {
        return delivery_method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_digital_delivery_selected.delivery_method
     *
     * @param delivery_method the value for order_transaction_digital_delivery_selected.delivery_method
     *
     * @mbggenerated
     */
    public void setDelivery_method(String delivery_method) {
        this.delivery_method = delivery_method == null ? null : delivery_method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_digital_delivery_selected.delivery_status_email
     *
     * @return the value of order_transaction_digital_delivery_selected.delivery_status_email
     *
     * @mbggenerated
     */
    public String getDelivery_status_email() {
        return delivery_status_email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_digital_delivery_selected.delivery_status_email
     *
     * @param delivery_status_email the value for order_transaction_digital_delivery_selected.delivery_status_email
     *
     * @mbggenerated
     */
    public void setDelivery_status_email(String delivery_status_email) {
        this.delivery_status_email = delivery_status_email == null ? null : delivery_status_email.trim();
    }
}