package yk.boxri.pojo;

import java.io.Serializable;

public class OrderTransactionTaxes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.transaction_id
     *
     * @mbggenerated
     */
    public String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.transaction_taxes_id
     *
     * @mbggenerated
     */
    public Integer transaction_taxes_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.imposition
     *
     * @mbggenerated
     */
    public String imposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.tax_amount
     *
     * @mbggenerated
     */
    public Double tax_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.tax_amount_currency_id
     *
     * @mbggenerated
     */
    public String tax_amount_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.tax_code
     *
     * @mbggenerated
     */
    public String tax_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.tax_description
     *
     * @mbggenerated
     */
    public String tax_description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.tax_on_handling_amount
     *
     * @mbggenerated
     */
    public Double tax_on_handling_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.tax_on_handling_amount_currency_id
     *
     * @mbggenerated
     */
    public String tax_on_handling_amount_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.tax_on_shipping_amount
     *
     * @mbggenerated
     */
    public Double tax_on_shipping_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.tax_on_shipping_amount_currency_id
     *
     * @mbggenerated
     */
    public String tax_on_shipping_amount_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.tax_on_subtotal_amount
     *
     * @mbggenerated
     */
    public Double tax_on_subtotal_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.tax_on_subtotal_amount_currency_id
     *
     * @mbggenerated
     */
    public String tax_on_subtotal_amount_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.tax_details
     *
     * @mbggenerated
     */
    public String tax_details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.total_tax_amount
     *
     * @mbggenerated
     */
    public Double total_tax_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_taxes.total_tax_amount_currency_id
     *
     * @mbggenerated
     */
    public String total_tax_amount_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_transaction_taxes
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.transaction_id
     *
     * @return the value of order_transaction_taxes.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.transaction_id
     *
     * @param transaction_id the value for order_transaction_taxes.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.transaction_taxes_id
     *
     * @return the value of order_transaction_taxes.transaction_taxes_id
     *
     * @mbggenerated
     */
    public Integer getTransaction_taxes_id() {
        return transaction_taxes_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.transaction_taxes_id
     *
     * @param transaction_taxes_id the value for order_transaction_taxes.transaction_taxes_id
     *
     * @mbggenerated
     */
    public void setTransaction_taxes_id(Integer transaction_taxes_id) {
        this.transaction_taxes_id = transaction_taxes_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.order_id
     *
     * @return the value of order_transaction_taxes.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.order_id
     *
     * @param order_id the value for order_transaction_taxes.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.user_id
     *
     * @return the value of order_transaction_taxes.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.user_id
     *
     * @param user_id the value for order_transaction_taxes.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.shop_id
     *
     * @return the value of order_transaction_taxes.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.shop_id
     *
     * @param shop_id the value for order_transaction_taxes.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.imposition
     *
     * @return the value of order_transaction_taxes.imposition
     *
     * @mbggenerated
     */
    public String getImposition() {
        return imposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.imposition
     *
     * @param imposition the value for order_transaction_taxes.imposition
     *
     * @mbggenerated
     */
    public void setImposition(String imposition) {
        this.imposition = imposition == null ? null : imposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.tax_amount
     *
     * @return the value of order_transaction_taxes.tax_amount
     *
     * @mbggenerated
     */
    public Double getTax_amount() {
        return tax_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.tax_amount
     *
     * @param tax_amount the value for order_transaction_taxes.tax_amount
     *
     * @mbggenerated
     */
    public void setTax_amount(Double tax_amount) {
        this.tax_amount = tax_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.tax_amount_currency_id
     *
     * @return the value of order_transaction_taxes.tax_amount_currency_id
     *
     * @mbggenerated
     */
    public String getTax_amount_currency_id() {
        return tax_amount_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.tax_amount_currency_id
     *
     * @param tax_amount_currency_id the value for order_transaction_taxes.tax_amount_currency_id
     *
     * @mbggenerated
     */
    public void setTax_amount_currency_id(String tax_amount_currency_id) {
        this.tax_amount_currency_id = tax_amount_currency_id == null ? null : tax_amount_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.tax_code
     *
     * @return the value of order_transaction_taxes.tax_code
     *
     * @mbggenerated
     */
    public String getTax_code() {
        return tax_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.tax_code
     *
     * @param tax_code the value for order_transaction_taxes.tax_code
     *
     * @mbggenerated
     */
    public void setTax_code(String tax_code) {
        this.tax_code = tax_code == null ? null : tax_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.tax_description
     *
     * @return the value of order_transaction_taxes.tax_description
     *
     * @mbggenerated
     */
    public String getTax_description() {
        return tax_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.tax_description
     *
     * @param tax_description the value for order_transaction_taxes.tax_description
     *
     * @mbggenerated
     */
    public void setTax_description(String tax_description) {
        this.tax_description = tax_description == null ? null : tax_description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.tax_on_handling_amount
     *
     * @return the value of order_transaction_taxes.tax_on_handling_amount
     *
     * @mbggenerated
     */
    public Double getTax_on_handling_amount() {
        return tax_on_handling_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.tax_on_handling_amount
     *
     * @param tax_on_handling_amount the value for order_transaction_taxes.tax_on_handling_amount
     *
     * @mbggenerated
     */
    public void setTax_on_handling_amount(Double tax_on_handling_amount) {
        this.tax_on_handling_amount = tax_on_handling_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.tax_on_handling_amount_currency_id
     *
     * @return the value of order_transaction_taxes.tax_on_handling_amount_currency_id
     *
     * @mbggenerated
     */
    public String getTax_on_handling_amount_currency_id() {
        return tax_on_handling_amount_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.tax_on_handling_amount_currency_id
     *
     * @param tax_on_handling_amount_currency_id the value for order_transaction_taxes.tax_on_handling_amount_currency_id
     *
     * @mbggenerated
     */
    public void setTax_on_handling_amount_currency_id(String tax_on_handling_amount_currency_id) {
        this.tax_on_handling_amount_currency_id = tax_on_handling_amount_currency_id == null ? null : tax_on_handling_amount_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.tax_on_shipping_amount
     *
     * @return the value of order_transaction_taxes.tax_on_shipping_amount
     *
     * @mbggenerated
     */
    public Double getTax_on_shipping_amount() {
        return tax_on_shipping_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.tax_on_shipping_amount
     *
     * @param tax_on_shipping_amount the value for order_transaction_taxes.tax_on_shipping_amount
     *
     * @mbggenerated
     */
    public void setTax_on_shipping_amount(Double tax_on_shipping_amount) {
        this.tax_on_shipping_amount = tax_on_shipping_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.tax_on_shipping_amount_currency_id
     *
     * @return the value of order_transaction_taxes.tax_on_shipping_amount_currency_id
     *
     * @mbggenerated
     */
    public String getTax_on_shipping_amount_currency_id() {
        return tax_on_shipping_amount_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.tax_on_shipping_amount_currency_id
     *
     * @param tax_on_shipping_amount_currency_id the value for order_transaction_taxes.tax_on_shipping_amount_currency_id
     *
     * @mbggenerated
     */
    public void setTax_on_shipping_amount_currency_id(String tax_on_shipping_amount_currency_id) {
        this.tax_on_shipping_amount_currency_id = tax_on_shipping_amount_currency_id == null ? null : tax_on_shipping_amount_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.tax_on_subtotal_amount
     *
     * @return the value of order_transaction_taxes.tax_on_subtotal_amount
     *
     * @mbggenerated
     */
    public Double getTax_on_subtotal_amount() {
        return tax_on_subtotal_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.tax_on_subtotal_amount
     *
     * @param tax_on_subtotal_amount the value for order_transaction_taxes.tax_on_subtotal_amount
     *
     * @mbggenerated
     */
    public void setTax_on_subtotal_amount(Double tax_on_subtotal_amount) {
        this.tax_on_subtotal_amount = tax_on_subtotal_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.tax_on_subtotal_amount_currency_id
     *
     * @return the value of order_transaction_taxes.tax_on_subtotal_amount_currency_id
     *
     * @mbggenerated
     */
    public String getTax_on_subtotal_amount_currency_id() {
        return tax_on_subtotal_amount_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.tax_on_subtotal_amount_currency_id
     *
     * @param tax_on_subtotal_amount_currency_id the value for order_transaction_taxes.tax_on_subtotal_amount_currency_id
     *
     * @mbggenerated
     */
    public void setTax_on_subtotal_amount_currency_id(String tax_on_subtotal_amount_currency_id) {
        this.tax_on_subtotal_amount_currency_id = tax_on_subtotal_amount_currency_id == null ? null : tax_on_subtotal_amount_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.tax_details
     *
     * @return the value of order_transaction_taxes.tax_details
     *
     * @mbggenerated
     */
    public String getTax_details() {
        return tax_details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.tax_details
     *
     * @param tax_details the value for order_transaction_taxes.tax_details
     *
     * @mbggenerated
     */
    public void setTax_details(String tax_details) {
        this.tax_details = tax_details == null ? null : tax_details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.total_tax_amount
     *
     * @return the value of order_transaction_taxes.total_tax_amount
     *
     * @mbggenerated
     */
    public Double getTotal_tax_amount() {
        return total_tax_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.total_tax_amount
     *
     * @param total_tax_amount the value for order_transaction_taxes.total_tax_amount
     *
     * @mbggenerated
     */
    public void setTotal_tax_amount(Double total_tax_amount) {
        this.total_tax_amount = total_tax_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_taxes.total_tax_amount_currency_id
     *
     * @return the value of order_transaction_taxes.total_tax_amount_currency_id
     *
     * @mbggenerated
     */
    public String getTotal_tax_amount_currency_id() {
        return total_tax_amount_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_taxes.total_tax_amount_currency_id
     *
     * @param total_tax_amount_currency_id the value for order_transaction_taxes.total_tax_amount_currency_id
     *
     * @mbggenerated
     */
    public void setTotal_tax_amount_currency_id(String total_tax_amount_currency_id) {
        this.total_tax_amount_currency_id = total_tax_amount_currency_id == null ? null : total_tax_amount_currency_id.trim();
    }
}