package yk.boxri.pojo;

import java.io.Serializable;

public class OrderShippingServiceSelected implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.expedited_service
     *
     * @mbggenerated
     */
    public Boolean expedited_service;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.import_charge
     *
     * @mbggenerated
     */
    public Double import_charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.import_charge_currency_id
     *
     * @mbggenerated
     */
    public String import_charge_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.logistic_plan_type
     *
     * @mbggenerated
     */
    public String logistic_plan_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.shipping_insurance_cost
     *
     * @mbggenerated
     */
    public Double shipping_insurance_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.shipping_insurance_cost_currency_id
     *
     * @mbggenerated
     */
    public String shipping_insurance_cost_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.shipping_package_info
     *
     * @mbggenerated
     */
    public String shipping_package_info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.shipping_service
     *
     * @mbggenerated
     */
    public String shipping_service;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.shipping_service_additional_cost
     *
     * @mbggenerated
     */
    public Double shipping_service_additional_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.shipping_service_additional_cost_currency_id
     *
     * @mbggenerated
     */
    public String shipping_service_additional_cost_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.shipping_service_cost
     *
     * @mbggenerated
     */
    public Double shipping_service_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.shipping_service_cost_currency_id
     *
     * @mbggenerated
     */
    public String shipping_service_cost_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_service_selected.shipping_service_priority
     *
     * @mbggenerated
     */
    public Integer shipping_service_priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_shipping_service_selected
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.order_id
     *
     * @return the value of order_shipping_service_selected.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.order_id
     *
     * @param order_id the value for order_shipping_service_selected.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.user_id
     *
     * @return the value of order_shipping_service_selected.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.user_id
     *
     * @param user_id the value for order_shipping_service_selected.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.shop_id
     *
     * @return the value of order_shipping_service_selected.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.shop_id
     *
     * @param shop_id the value for order_shipping_service_selected.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.expedited_service
     *
     * @return the value of order_shipping_service_selected.expedited_service
     *
     * @mbggenerated
     */
    public Boolean getExpedited_service() {
        return expedited_service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.expedited_service
     *
     * @param expedited_service the value for order_shipping_service_selected.expedited_service
     *
     * @mbggenerated
     */
    public void setExpedited_service(Boolean expedited_service) {
        this.expedited_service = expedited_service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.import_charge
     *
     * @return the value of order_shipping_service_selected.import_charge
     *
     * @mbggenerated
     */
    public Double getImport_charge() {
        return import_charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.import_charge
     *
     * @param import_charge the value for order_shipping_service_selected.import_charge
     *
     * @mbggenerated
     */
    public void setImport_charge(Double import_charge) {
        this.import_charge = import_charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.import_charge_currency_id
     *
     * @return the value of order_shipping_service_selected.import_charge_currency_id
     *
     * @mbggenerated
     */
    public String getImport_charge_currency_id() {
        return import_charge_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.import_charge_currency_id
     *
     * @param import_charge_currency_id the value for order_shipping_service_selected.import_charge_currency_id
     *
     * @mbggenerated
     */
    public void setImport_charge_currency_id(String import_charge_currency_id) {
        this.import_charge_currency_id = import_charge_currency_id == null ? null : import_charge_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.logistic_plan_type
     *
     * @return the value of order_shipping_service_selected.logistic_plan_type
     *
     * @mbggenerated
     */
    public String getLogistic_plan_type() {
        return logistic_plan_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.logistic_plan_type
     *
     * @param logistic_plan_type the value for order_shipping_service_selected.logistic_plan_type
     *
     * @mbggenerated
     */
    public void setLogistic_plan_type(String logistic_plan_type) {
        this.logistic_plan_type = logistic_plan_type == null ? null : logistic_plan_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.shipping_insurance_cost
     *
     * @return the value of order_shipping_service_selected.shipping_insurance_cost
     *
     * @mbggenerated
     */
    public Double getShipping_insurance_cost() {
        return shipping_insurance_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.shipping_insurance_cost
     *
     * @param shipping_insurance_cost the value for order_shipping_service_selected.shipping_insurance_cost
     *
     * @mbggenerated
     */
    public void setShipping_insurance_cost(Double shipping_insurance_cost) {
        this.shipping_insurance_cost = shipping_insurance_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.shipping_insurance_cost_currency_id
     *
     * @return the value of order_shipping_service_selected.shipping_insurance_cost_currency_id
     *
     * @mbggenerated
     */
    public String getShipping_insurance_cost_currency_id() {
        return shipping_insurance_cost_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.shipping_insurance_cost_currency_id
     *
     * @param shipping_insurance_cost_currency_id the value for order_shipping_service_selected.shipping_insurance_cost_currency_id
     *
     * @mbggenerated
     */
    public void setShipping_insurance_cost_currency_id(String shipping_insurance_cost_currency_id) {
        this.shipping_insurance_cost_currency_id = shipping_insurance_cost_currency_id == null ? null : shipping_insurance_cost_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.shipping_package_info
     *
     * @return the value of order_shipping_service_selected.shipping_package_info
     *
     * @mbggenerated
     */
    public String getShipping_package_info() {
        return shipping_package_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.shipping_package_info
     *
     * @param shipping_package_info the value for order_shipping_service_selected.shipping_package_info
     *
     * @mbggenerated
     */
    public void setShipping_package_info(String shipping_package_info) {
        this.shipping_package_info = shipping_package_info == null ? null : shipping_package_info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.shipping_service
     *
     * @return the value of order_shipping_service_selected.shipping_service
     *
     * @mbggenerated
     */
    public String getShipping_service() {
        return shipping_service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.shipping_service
     *
     * @param shipping_service the value for order_shipping_service_selected.shipping_service
     *
     * @mbggenerated
     */
    public void setShipping_service(String shipping_service) {
        this.shipping_service = shipping_service == null ? null : shipping_service.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.shipping_service_additional_cost
     *
     * @return the value of order_shipping_service_selected.shipping_service_additional_cost
     *
     * @mbggenerated
     */
    public Double getShipping_service_additional_cost() {
        return shipping_service_additional_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.shipping_service_additional_cost
     *
     * @param shipping_service_additional_cost the value for order_shipping_service_selected.shipping_service_additional_cost
     *
     * @mbggenerated
     */
    public void setShipping_service_additional_cost(Double shipping_service_additional_cost) {
        this.shipping_service_additional_cost = shipping_service_additional_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.shipping_service_additional_cost_currency_id
     *
     * @return the value of order_shipping_service_selected.shipping_service_additional_cost_currency_id
     *
     * @mbggenerated
     */
    public String getShipping_service_additional_cost_currency_id() {
        return shipping_service_additional_cost_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.shipping_service_additional_cost_currency_id
     *
     * @param shipping_service_additional_cost_currency_id the value for order_shipping_service_selected.shipping_service_additional_cost_currency_id
     *
     * @mbggenerated
     */
    public void setShipping_service_additional_cost_currency_id(String shipping_service_additional_cost_currency_id) {
        this.shipping_service_additional_cost_currency_id = shipping_service_additional_cost_currency_id == null ? null : shipping_service_additional_cost_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.shipping_service_cost
     *
     * @return the value of order_shipping_service_selected.shipping_service_cost
     *
     * @mbggenerated
     */
    public Double getShipping_service_cost() {
        return shipping_service_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.shipping_service_cost
     *
     * @param shipping_service_cost the value for order_shipping_service_selected.shipping_service_cost
     *
     * @mbggenerated
     */
    public void setShipping_service_cost(Double shipping_service_cost) {
        this.shipping_service_cost = shipping_service_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.shipping_service_cost_currency_id
     *
     * @return the value of order_shipping_service_selected.shipping_service_cost_currency_id
     *
     * @mbggenerated
     */
    public String getShipping_service_cost_currency_id() {
        return shipping_service_cost_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.shipping_service_cost_currency_id
     *
     * @param shipping_service_cost_currency_id the value for order_shipping_service_selected.shipping_service_cost_currency_id
     *
     * @mbggenerated
     */
    public void setShipping_service_cost_currency_id(String shipping_service_cost_currency_id) {
        this.shipping_service_cost_currency_id = shipping_service_cost_currency_id == null ? null : shipping_service_cost_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_service_selected.shipping_service_priority
     *
     * @return the value of order_shipping_service_selected.shipping_service_priority
     *
     * @mbggenerated
     */
    public Integer getShipping_service_priority() {
        return shipping_service_priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_service_selected.shipping_service_priority
     *
     * @param shipping_service_priority the value for order_shipping_service_selected.shipping_service_priority
     *
     * @mbggenerated
     */
    public void setShipping_service_priority(Integer shipping_service_priority) {
        this.shipping_service_priority = shipping_service_priority;
    }
}