package yk.boxri.pojo;

import java.io.Serializable;
import java.util.Date;

public class OrderTransactionExternalTransaction implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_external_transaction.transaction_id
     *
     * @mbggenerated
     */
    public String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_external_transaction.transaction_external_transaction_id
     *
     * @mbggenerated
     */
    public Integer transaction_external_transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_external_transaction.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_external_transaction.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_external_transaction.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_external_transaction.external_transaction_id
     *
     * @mbggenerated
     */
    public String external_transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_external_transaction.external_transaction_status
     *
     * @mbggenerated
     */
    public String external_transaction_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_external_transaction.external_transaction_time
     *
     * @mbggenerated
     */
    public Date external_transaction_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_external_transaction.fee_or_credit_amount
     *
     * @mbggenerated
     */
    public Double fee_or_credit_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_external_transaction.fee_or_credit_amount_currency_id
     *
     * @mbggenerated
     */
    public String fee_or_credit_amount_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_external_transaction.payment_or_refund_amount
     *
     * @mbggenerated
     */
    public Double payment_or_refund_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_external_transaction.payment_or_refund_amount_currency_id
     *
     * @mbggenerated
     */
    public String payment_or_refund_amount_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_transaction_external_transaction
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_external_transaction.transaction_id
     *
     * @return the value of order_transaction_external_transaction.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_external_transaction.transaction_id
     *
     * @param transaction_id the value for order_transaction_external_transaction.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_external_transaction.transaction_external_transaction_id
     *
     * @return the value of order_transaction_external_transaction.transaction_external_transaction_id
     *
     * @mbggenerated
     */
    public Integer getTransaction_external_transaction_id() {
        return transaction_external_transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_external_transaction.transaction_external_transaction_id
     *
     * @param transaction_external_transaction_id the value for order_transaction_external_transaction.transaction_external_transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_external_transaction_id(Integer transaction_external_transaction_id) {
        this.transaction_external_transaction_id = transaction_external_transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_external_transaction.order_id
     *
     * @return the value of order_transaction_external_transaction.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_external_transaction.order_id
     *
     * @param order_id the value for order_transaction_external_transaction.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_external_transaction.user_id
     *
     * @return the value of order_transaction_external_transaction.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_external_transaction.user_id
     *
     * @param user_id the value for order_transaction_external_transaction.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_external_transaction.shop_id
     *
     * @return the value of order_transaction_external_transaction.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_external_transaction.shop_id
     *
     * @param shop_id the value for order_transaction_external_transaction.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_external_transaction.external_transaction_id
     *
     * @return the value of order_transaction_external_transaction.external_transaction_id
     *
     * @mbggenerated
     */
    public String getExternal_transaction_id() {
        return external_transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_external_transaction.external_transaction_id
     *
     * @param external_transaction_id the value for order_transaction_external_transaction.external_transaction_id
     *
     * @mbggenerated
     */
    public void setExternal_transaction_id(String external_transaction_id) {
        this.external_transaction_id = external_transaction_id == null ? null : external_transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_external_transaction.external_transaction_status
     *
     * @return the value of order_transaction_external_transaction.external_transaction_status
     *
     * @mbggenerated
     */
    public String getExternal_transaction_status() {
        return external_transaction_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_external_transaction.external_transaction_status
     *
     * @param external_transaction_status the value for order_transaction_external_transaction.external_transaction_status
     *
     * @mbggenerated
     */
    public void setExternal_transaction_status(String external_transaction_status) {
        this.external_transaction_status = external_transaction_status == null ? null : external_transaction_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_external_transaction.external_transaction_time
     *
     * @return the value of order_transaction_external_transaction.external_transaction_time
     *
     * @mbggenerated
     */
    public Date getExternal_transaction_time() {
        return external_transaction_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_external_transaction.external_transaction_time
     *
     * @param external_transaction_time the value for order_transaction_external_transaction.external_transaction_time
     *
     * @mbggenerated
     */
    public void setExternal_transaction_time(Date external_transaction_time) {
        this.external_transaction_time = external_transaction_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_external_transaction.fee_or_credit_amount
     *
     * @return the value of order_transaction_external_transaction.fee_or_credit_amount
     *
     * @mbggenerated
     */
    public Double getFee_or_credit_amount() {
        return fee_or_credit_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_external_transaction.fee_or_credit_amount
     *
     * @param fee_or_credit_amount the value for order_transaction_external_transaction.fee_or_credit_amount
     *
     * @mbggenerated
     */
    public void setFee_or_credit_amount(Double fee_or_credit_amount) {
        this.fee_or_credit_amount = fee_or_credit_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_external_transaction.fee_or_credit_amount_currency_id
     *
     * @return the value of order_transaction_external_transaction.fee_or_credit_amount_currency_id
     *
     * @mbggenerated
     */
    public String getFee_or_credit_amount_currency_id() {
        return fee_or_credit_amount_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_external_transaction.fee_or_credit_amount_currency_id
     *
     * @param fee_or_credit_amount_currency_id the value for order_transaction_external_transaction.fee_or_credit_amount_currency_id
     *
     * @mbggenerated
     */
    public void setFee_or_credit_amount_currency_id(String fee_or_credit_amount_currency_id) {
        this.fee_or_credit_amount_currency_id = fee_or_credit_amount_currency_id == null ? null : fee_or_credit_amount_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_external_transaction.payment_or_refund_amount
     *
     * @return the value of order_transaction_external_transaction.payment_or_refund_amount
     *
     * @mbggenerated
     */
    public Double getPayment_or_refund_amount() {
        return payment_or_refund_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_external_transaction.payment_or_refund_amount
     *
     * @param payment_or_refund_amount the value for order_transaction_external_transaction.payment_or_refund_amount
     *
     * @mbggenerated
     */
    public void setPayment_or_refund_amount(Double payment_or_refund_amount) {
        this.payment_or_refund_amount = payment_or_refund_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_external_transaction.payment_or_refund_amount_currency_id
     *
     * @return the value of order_transaction_external_transaction.payment_or_refund_amount_currency_id
     *
     * @mbggenerated
     */
    public String getPayment_or_refund_amount_currency_id() {
        return payment_or_refund_amount_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_external_transaction.payment_or_refund_amount_currency_id
     *
     * @param payment_or_refund_amount_currency_id the value for order_transaction_external_transaction.payment_or_refund_amount_currency_id
     *
     * @mbggenerated
     */
    public void setPayment_or_refund_amount_currency_id(String payment_or_refund_amount_currency_id) {
        this.payment_or_refund_amount_currency_id = payment_or_refund_amount_currency_id == null ? null : payment_or_refund_amount_currency_id.trim();
    }
}