package yk.boxri.pojo;

import java.io.Serializable;

public class OrderTransactionItem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_item.transaction_id
     *
     * @mbggenerated
     */
    public String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_item.item_id
     *
     * @mbggenerated
     */
    public String item_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_item.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_item.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_item.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_item.attribute_array
     *
     * @mbggenerated
     */
    public String attribute_array;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_item.integrated_merchant_credit_card_enabled
     *
     * @mbggenerated
     */
    public Boolean integrated_merchant_credit_card_enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_item.public_notes
     *
     * @mbggenerated
     */
    public String public_notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_item.seller_inventory_id
     *
     * @mbggenerated
     */
    public String seller_inventory_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_item.site
     *
     * @mbggenerated
     */
    public String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_item.SKU
     *
     * @mbggenerated
     */
    public String SKU;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_item.title
     *
     * @mbggenerated
     */
    public String title;

	public String private_notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_transaction_item
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_item.transaction_id
     *
     * @return the value of order_transaction_item.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_item.transaction_id
     *
     * @param transaction_id the value for order_transaction_item.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_item.item_id
     *
     * @return the value of order_transaction_item.item_id
     *
     * @mbggenerated
     */
    public String getItem_id() {
        return item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_item.item_id
     *
     * @param item_id the value for order_transaction_item.item_id
     *
     * @mbggenerated
     */
    public void setItem_id(String item_id) {
        this.item_id = item_id == null ? null : item_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_item.order_id
     *
     * @return the value of order_transaction_item.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_item.order_id
     *
     * @param order_id the value for order_transaction_item.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_item.user_id
     *
     * @return the value of order_transaction_item.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_item.user_id
     *
     * @param user_id the value for order_transaction_item.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_item.shop_id
     *
     * @return the value of order_transaction_item.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_item.shop_id
     *
     * @param shop_id the value for order_transaction_item.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_item.attribute_array
     *
     * @return the value of order_transaction_item.attribute_array
     *
     * @mbggenerated
     */
    public String getAttribute_array() {
        return attribute_array;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_item.attribute_array
     *
     * @param attribute_array the value for order_transaction_item.attribute_array
     *
     * @mbggenerated
     */
    public void setAttribute_array(String attribute_array) {
        this.attribute_array = attribute_array == null ? null : attribute_array.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_item.integrated_merchant_credit_card_enabled
     *
     * @return the value of order_transaction_item.integrated_merchant_credit_card_enabled
     *
     * @mbggenerated
     */
    public Boolean getIntegrated_merchant_credit_card_enabled() {
        return integrated_merchant_credit_card_enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_item.integrated_merchant_credit_card_enabled
     *
     * @param integrated_merchant_credit_card_enabled the value for order_transaction_item.integrated_merchant_credit_card_enabled
     *
     * @mbggenerated
     */
    public void setIntegrated_merchant_credit_card_enabled(Boolean integrated_merchant_credit_card_enabled) {
        this.integrated_merchant_credit_card_enabled = integrated_merchant_credit_card_enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_item.public_notes
     *
     * @return the value of order_transaction_item.public_notes
     *
     * @mbggenerated
     */
    public String getpublic_notes() {
        return public_notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_item.public_notes
     *
     * @param public_notes the value for order_transaction_item.public_notes
     *
     * @mbggenerated
     */
    public void setpublic_notes(String public_notes) {
        this.public_notes = public_notes == null ? null : public_notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_item.seller_inventory_id
     *
     * @return the value of order_transaction_item.seller_inventory_id
     *
     * @mbggenerated
     */
    public String getSeller_inventory_id() {
        return seller_inventory_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_item.seller_inventory_id
     *
     * @param seller_inventory_id the value for order_transaction_item.seller_inventory_id
     *
     * @mbggenerated
     */
    public void setSeller_inventory_id(String seller_inventory_id) {
        this.seller_inventory_id = seller_inventory_id == null ? null : seller_inventory_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_item.site
     *
     * @return the value of order_transaction_item.site
     *
     * @mbggenerated
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_item.site
     *
     * @param site the value for order_transaction_item.site
     *
     * @mbggenerated
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_item.SKU
     *
     * @return the value of order_transaction_item.SKU
     *
     * @mbggenerated
     */
    public String getSKU() {
        return SKU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_item.SKU
     *
     * @param SKU the value for order_transaction_item.SKU
     *
     * @mbggenerated
     */
    public void setSKU(String SKU) {
        this.SKU = SKU == null ? null : SKU.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_item.title
     *
     * @return the value of order_transaction_item.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_item.title
     *
     * @param title the value for order_transaction_item.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}