package yk.boxri.pojo;

import java.io.Serializable;
import java.util.Date;

public class OrderTransactionPaymentHoldDetails implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_payment_hold_details.transaction_id
     *
     * @mbggenerated
     */
    public String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_payment_hold_details.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_payment_hold_details.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_payment_hold_details.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_payment_hold_details.expected_release_date
     *
     * @mbggenerated
     */
    public Date expected_release_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_payment_hold_details.num_of_req_seller_actions
     *
     * @mbggenerated
     */
    public Integer num_of_req_seller_actions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_payment_hold_details.payment_hold_reason
     *
     * @mbggenerated
     */
    public String payment_hold_reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_payment_hold_details.required_seller_action_values
     *
     * @mbggenerated
     */
    public String required_seller_action_values;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_transaction_payment_hold_details
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_payment_hold_details.transaction_id
     *
     * @return the value of order_transaction_payment_hold_details.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_payment_hold_details.transaction_id
     *
     * @param transaction_id the value for order_transaction_payment_hold_details.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_payment_hold_details.order_id
     *
     * @return the value of order_transaction_payment_hold_details.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_payment_hold_details.order_id
     *
     * @param order_id the value for order_transaction_payment_hold_details.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_payment_hold_details.user_id
     *
     * @return the value of order_transaction_payment_hold_details.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_payment_hold_details.user_id
     *
     * @param user_id the value for order_transaction_payment_hold_details.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_payment_hold_details.shop_id
     *
     * @return the value of order_transaction_payment_hold_details.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_payment_hold_details.shop_id
     *
     * @param shop_id the value for order_transaction_payment_hold_details.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_payment_hold_details.expected_release_date
     *
     * @return the value of order_transaction_payment_hold_details.expected_release_date
     *
     * @mbggenerated
     */
    public Date getExpected_release_date() {
        return expected_release_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_payment_hold_details.expected_release_date
     *
     * @param expected_release_date the value for order_transaction_payment_hold_details.expected_release_date
     *
     * @mbggenerated
     */
    public void setExpected_release_date(Date expected_release_date) {
        this.expected_release_date = expected_release_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_payment_hold_details.num_of_req_seller_actions
     *
     * @return the value of order_transaction_payment_hold_details.num_of_req_seller_actions
     *
     * @mbggenerated
     */
    public Integer getNum_of_req_seller_actions() {
        return num_of_req_seller_actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_payment_hold_details.num_of_req_seller_actions
     *
     * @param num_of_req_seller_actions the value for order_transaction_payment_hold_details.num_of_req_seller_actions
     *
     * @mbggenerated
     */
    public void setNum_of_req_seller_actions(Integer num_of_req_seller_actions) {
        this.num_of_req_seller_actions = num_of_req_seller_actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_payment_hold_details.payment_hold_reason
     *
     * @return the value of order_transaction_payment_hold_details.payment_hold_reason
     *
     * @mbggenerated
     */
    public String getPayment_hold_reason() {
        return payment_hold_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_payment_hold_details.payment_hold_reason
     *
     * @param payment_hold_reason the value for order_transaction_payment_hold_details.payment_hold_reason
     *
     * @mbggenerated
     */
    public void setPayment_hold_reason(String payment_hold_reason) {
        this.payment_hold_reason = payment_hold_reason == null ? null : payment_hold_reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_payment_hold_details.required_seller_action_values
     *
     * @return the value of order_transaction_payment_hold_details.required_seller_action_values
     *
     * @mbggenerated
     */
    public String getRequired_seller_action_values() {
        return required_seller_action_values;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_payment_hold_details.required_seller_action_values
     *
     * @param required_seller_action_values the value for order_transaction_payment_hold_details.required_seller_action_values
     *
     * @mbggenerated
     */
    public void setRequired_seller_action_values(String required_seller_action_values) {
        this.required_seller_action_values = required_seller_action_values == null ? null : required_seller_action_values.trim();
    }
}