package yk.boxri.pojo;

import java.io.Serializable;

public class OrderTransactionMultilegShippingDetails implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.transaction_id
     *
     * @mbggenerated
     */
    public String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.shipping_service
     *
     * @mbggenerated
     */
    public String shipping_service;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.total_shipping_cost
     *
     * @mbggenerated
     */
    public Double total_shipping_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.total_shipping_cost_currency_id
     *
     * @mbggenerated
     */
    public String total_shipping_cost_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.shipping_time_max
     *
     * @mbggenerated
     */
    public Integer shipping_time_max;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.shipping_time_min
     *
     * @mbggenerated
     */
    public Integer shipping_time_min;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.address_attribute_value
     *
     * @mbggenerated
     */
    public String address_attribute_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.address_id
     *
     * @mbggenerated
     */
    public String address_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.address_owner
     *
     * @mbggenerated
     */
    public String address_owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.address_usage
     *
     * @mbggenerated
     */
    public String address_usage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.city_name
     *
     * @mbggenerated
     */
    public String city_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.country
     *
     * @mbggenerated
     */
    public String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.country_name
     *
     * @mbggenerated
     */
    public String country_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.external_address_id
     *
     * @mbggenerated
     */
    public String external_address_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.name
     *
     * @mbggenerated
     */
    public String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.phone
     *
     * @mbggenerated
     */
    public String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.postal_code
     *
     * @mbggenerated
     */
    public String postal_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.reference_id
     *
     * @mbggenerated
     */
    public String reference_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.state_or_province
     *
     * @mbggenerated
     */
    public String state_or_province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.street1
     *
     * @mbggenerated
     */
    public String street1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_multileg_shipping_details.street2
     *
     * @mbggenerated
     */
    public String street2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_transaction_multileg_shipping_details
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.transaction_id
     *
     * @return the value of order_transaction_multileg_shipping_details.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.transaction_id
     *
     * @param transaction_id the value for order_transaction_multileg_shipping_details.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.order_id
     *
     * @return the value of order_transaction_multileg_shipping_details.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.order_id
     *
     * @param order_id the value for order_transaction_multileg_shipping_details.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.user_id
     *
     * @return the value of order_transaction_multileg_shipping_details.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.user_id
     *
     * @param user_id the value for order_transaction_multileg_shipping_details.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.shop_id
     *
     * @return the value of order_transaction_multileg_shipping_details.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.shop_id
     *
     * @param shop_id the value for order_transaction_multileg_shipping_details.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.shipping_service
     *
     * @return the value of order_transaction_multileg_shipping_details.shipping_service
     *
     * @mbggenerated
     */
    public String getShipping_service() {
        return shipping_service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.shipping_service
     *
     * @param shipping_service the value for order_transaction_multileg_shipping_details.shipping_service
     *
     * @mbggenerated
     */
    public void setShipping_service(String shipping_service) {
        this.shipping_service = shipping_service == null ? null : shipping_service.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.total_shipping_cost
     *
     * @return the value of order_transaction_multileg_shipping_details.total_shipping_cost
     *
     * @mbggenerated
     */
    public Double getTotal_shipping_cost() {
        return total_shipping_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.total_shipping_cost
     *
     * @param total_shipping_cost the value for order_transaction_multileg_shipping_details.total_shipping_cost
     *
     * @mbggenerated
     */
    public void setTotal_shipping_cost(Double total_shipping_cost) {
        this.total_shipping_cost = total_shipping_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.total_shipping_cost_currency_id
     *
     * @return the value of order_transaction_multileg_shipping_details.total_shipping_cost_currency_id
     *
     * @mbggenerated
     */
    public String getTotal_shipping_cost_currency_id() {
        return total_shipping_cost_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.total_shipping_cost_currency_id
     *
     * @param total_shipping_cost_currency_id the value for order_transaction_multileg_shipping_details.total_shipping_cost_currency_id
     *
     * @mbggenerated
     */
    public void setTotal_shipping_cost_currency_id(String total_shipping_cost_currency_id) {
        this.total_shipping_cost_currency_id = total_shipping_cost_currency_id == null ? null : total_shipping_cost_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.shipping_time_max
     *
     * @return the value of order_transaction_multileg_shipping_details.shipping_time_max
     *
     * @mbggenerated
     */
    public Integer getShipping_time_max() {
        return shipping_time_max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.shipping_time_max
     *
     * @param shipping_time_max the value for order_transaction_multileg_shipping_details.shipping_time_max
     *
     * @mbggenerated
     */
    public void setShipping_time_max(Integer shipping_time_max) {
        this.shipping_time_max = shipping_time_max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.shipping_time_min
     *
     * @return the value of order_transaction_multileg_shipping_details.shipping_time_min
     *
     * @mbggenerated
     */
    public Integer getShipping_time_min() {
        return shipping_time_min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.shipping_time_min
     *
     * @param shipping_time_min the value for order_transaction_multileg_shipping_details.shipping_time_min
     *
     * @mbggenerated
     */
    public void setShipping_time_min(Integer shipping_time_min) {
        this.shipping_time_min = shipping_time_min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.address_attribute_value
     *
     * @return the value of order_transaction_multileg_shipping_details.address_attribute_value
     *
     * @mbggenerated
     */
    public String getAddress_attribute_value() {
        return address_attribute_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.address_attribute_value
     *
     * @param address_attribute_value the value for order_transaction_multileg_shipping_details.address_attribute_value
     *
     * @mbggenerated
     */
    public void setAddress_attribute_value(String address_attribute_value) {
        this.address_attribute_value = address_attribute_value == null ? null : address_attribute_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.address_id
     *
     * @return the value of order_transaction_multileg_shipping_details.address_id
     *
     * @mbggenerated
     */
    public String getAddress_id() {
        return address_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.address_id
     *
     * @param address_id the value for order_transaction_multileg_shipping_details.address_id
     *
     * @mbggenerated
     */
    public void setAddress_id(String address_id) {
        this.address_id = address_id == null ? null : address_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.address_owner
     *
     * @return the value of order_transaction_multileg_shipping_details.address_owner
     *
     * @mbggenerated
     */
    public String getAddress_owner() {
        return address_owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.address_owner
     *
     * @param address_owner the value for order_transaction_multileg_shipping_details.address_owner
     *
     * @mbggenerated
     */
    public void setAddress_owner(String address_owner) {
        this.address_owner = address_owner == null ? null : address_owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.address_usage
     *
     * @return the value of order_transaction_multileg_shipping_details.address_usage
     *
     * @mbggenerated
     */
    public String getAddress_usage() {
        return address_usage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.address_usage
     *
     * @param address_usage the value for order_transaction_multileg_shipping_details.address_usage
     *
     * @mbggenerated
     */
    public void setAddress_usage(String address_usage) {
        this.address_usage = address_usage == null ? null : address_usage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.city_name
     *
     * @return the value of order_transaction_multileg_shipping_details.city_name
     *
     * @mbggenerated
     */
    public String getCity_name() {
        return city_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.city_name
     *
     * @param city_name the value for order_transaction_multileg_shipping_details.city_name
     *
     * @mbggenerated
     */
    public void setCity_name(String city_name) {
        this.city_name = city_name == null ? null : city_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.country
     *
     * @return the value of order_transaction_multileg_shipping_details.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.country
     *
     * @param country the value for order_transaction_multileg_shipping_details.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.country_name
     *
     * @return the value of order_transaction_multileg_shipping_details.country_name
     *
     * @mbggenerated
     */
    public String getCountry_name() {
        return country_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.country_name
     *
     * @param country_name the value for order_transaction_multileg_shipping_details.country_name
     *
     * @mbggenerated
     */
    public void setCountry_name(String country_name) {
        this.country_name = country_name == null ? null : country_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.external_address_id
     *
     * @return the value of order_transaction_multileg_shipping_details.external_address_id
     *
     * @mbggenerated
     */
    public String getExternal_address_id() {
        return external_address_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.external_address_id
     *
     * @param external_address_id the value for order_transaction_multileg_shipping_details.external_address_id
     *
     * @mbggenerated
     */
    public void setExternal_address_id(String external_address_id) {
        this.external_address_id = external_address_id == null ? null : external_address_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.name
     *
     * @return the value of order_transaction_multileg_shipping_details.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.name
     *
     * @param name the value for order_transaction_multileg_shipping_details.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.phone
     *
     * @return the value of order_transaction_multileg_shipping_details.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.phone
     *
     * @param phone the value for order_transaction_multileg_shipping_details.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.postal_code
     *
     * @return the value of order_transaction_multileg_shipping_details.postal_code
     *
     * @mbggenerated
     */
    public String getPostal_code() {
        return postal_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.postal_code
     *
     * @param postal_code the value for order_transaction_multileg_shipping_details.postal_code
     *
     * @mbggenerated
     */
    public void setPostal_code(String postal_code) {
        this.postal_code = postal_code == null ? null : postal_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.reference_id
     *
     * @return the value of order_transaction_multileg_shipping_details.reference_id
     *
     * @mbggenerated
     */
    public String getReference_id() {
        return reference_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.reference_id
     *
     * @param reference_id the value for order_transaction_multileg_shipping_details.reference_id
     *
     * @mbggenerated
     */
    public void setReference_id(String reference_id) {
        this.reference_id = reference_id == null ? null : reference_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.state_or_province
     *
     * @return the value of order_transaction_multileg_shipping_details.state_or_province
     *
     * @mbggenerated
     */
    public String getState_or_province() {
        return state_or_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.state_or_province
     *
     * @param state_or_province the value for order_transaction_multileg_shipping_details.state_or_province
     *
     * @mbggenerated
     */
    public void setState_or_province(String state_or_province) {
        this.state_or_province = state_or_province == null ? null : state_or_province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.street1
     *
     * @return the value of order_transaction_multileg_shipping_details.street1
     *
     * @mbggenerated
     */
    public String getStreet1() {
        return street1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.street1
     *
     * @param street1 the value for order_transaction_multileg_shipping_details.street1
     *
     * @mbggenerated
     */
    public void setStreet1(String street1) {
        this.street1 = street1 == null ? null : street1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_multileg_shipping_details.street2
     *
     * @return the value of order_transaction_multileg_shipping_details.street2
     *
     * @mbggenerated
     */
    public String getStreet2() {
        return street2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_multileg_shipping_details.street2
     *
     * @param street2 the value for order_transaction_multileg_shipping_details.street2
     *
     * @mbggenerated
     */
    public void setStreet2(String street2) {
        this.street2 = street2 == null ? null : street2.trim();
    }
}