package yk.boxri.pojo;

import java.io.Serializable;

public class OrderTransactionSellerDiscount implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_seller_discount.transaction_id
     *
     * @mbggenerated
     */
    public String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_seller_discount.transaction_seller_discount_id
     *
     * @mbggenerated
     */
    public Integer transaction_seller_discount_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_seller_discount.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_seller_discount.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_seller_discount.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_seller_discount.original_item_price
     *
     * @mbggenerated
     */
    public Double original_item_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_seller_discount.original_item_price_currency_id
     *
     * @mbggenerated
     */
    public String original_item_price_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_seller_discount.original_item_shipping_cost
     *
     * @mbggenerated
     */
    public Double original_item_shipping_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_seller_discount.original_item_shipping_currency_id
     *
     * @mbggenerated
     */
    public String original_item_shipping_currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_seller_discount.original_shipping_service
     *
     * @mbggenerated
     */
    public String original_shipping_service;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_transaction_seller_discount.seller_discount
     *
     * @mbggenerated
     */
    public String seller_discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_transaction_seller_discount
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_seller_discount.transaction_id
     *
     * @return the value of order_transaction_seller_discount.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_seller_discount.transaction_id
     *
     * @param transaction_id the value for order_transaction_seller_discount.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_seller_discount.transaction_seller_discount_id
     *
     * @return the value of order_transaction_seller_discount.transaction_seller_discount_id
     *
     * @mbggenerated
     */
    public Integer getTransaction_seller_discount_id() {
        return transaction_seller_discount_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_seller_discount.transaction_seller_discount_id
     *
     * @param transaction_seller_discount_id the value for order_transaction_seller_discount.transaction_seller_discount_id
     *
     * @mbggenerated
     */
    public void setTransaction_seller_discount_id(Integer transaction_seller_discount_id) {
        this.transaction_seller_discount_id = transaction_seller_discount_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_seller_discount.order_id
     *
     * @return the value of order_transaction_seller_discount.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_seller_discount.order_id
     *
     * @param order_id the value for order_transaction_seller_discount.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_seller_discount.user_id
     *
     * @return the value of order_transaction_seller_discount.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_seller_discount.user_id
     *
     * @param user_id the value for order_transaction_seller_discount.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_seller_discount.shop_id
     *
     * @return the value of order_transaction_seller_discount.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_seller_discount.shop_id
     *
     * @param shop_id the value for order_transaction_seller_discount.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_seller_discount.original_item_price
     *
     * @return the value of order_transaction_seller_discount.original_item_price
     *
     * @mbggenerated
     */
    public Double getOriginal_item_price() {
        return original_item_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_seller_discount.original_item_price
     *
     * @param original_item_price the value for order_transaction_seller_discount.original_item_price
     *
     * @mbggenerated
     */
    public void setOriginal_item_price(Double original_item_price) {
        this.original_item_price = original_item_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_seller_discount.original_item_price_currency_id
     *
     * @return the value of order_transaction_seller_discount.original_item_price_currency_id
     *
     * @mbggenerated
     */
    public String getOriginal_item_price_currency_id() {
        return original_item_price_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_seller_discount.original_item_price_currency_id
     *
     * @param original_item_price_currency_id the value for order_transaction_seller_discount.original_item_price_currency_id
     *
     * @mbggenerated
     */
    public void setOriginal_item_price_currency_id(String original_item_price_currency_id) {
        this.original_item_price_currency_id = original_item_price_currency_id == null ? null : original_item_price_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_seller_discount.original_item_shipping_cost
     *
     * @return the value of order_transaction_seller_discount.original_item_shipping_cost
     *
     * @mbggenerated
     */
    public Double getOriginal_item_shipping_cost() {
        return original_item_shipping_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_seller_discount.original_item_shipping_cost
     *
     * @param original_item_shipping_cost the value for order_transaction_seller_discount.original_item_shipping_cost
     *
     * @mbggenerated
     */
    public void setOriginal_item_shipping_cost(Double original_item_shipping_cost) {
        this.original_item_shipping_cost = original_item_shipping_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_seller_discount.original_item_shipping_currency_id
     *
     * @return the value of order_transaction_seller_discount.original_item_shipping_currency_id
     *
     * @mbggenerated
     */
    public String getOriginal_item_shipping_currency_id() {
        return original_item_shipping_currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_seller_discount.original_item_shipping_currency_id
     *
     * @param original_item_shipping_currency_id the value for order_transaction_seller_discount.original_item_shipping_currency_id
     *
     * @mbggenerated
     */
    public void setOriginal_item_shipping_currency_id(String original_item_shipping_currency_id) {
        this.original_item_shipping_currency_id = original_item_shipping_currency_id == null ? null : original_item_shipping_currency_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_seller_discount.original_shipping_service
     *
     * @return the value of order_transaction_seller_discount.original_shipping_service
     *
     * @mbggenerated
     */
    public String getOriginal_shipping_service() {
        return original_shipping_service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_seller_discount.original_shipping_service
     *
     * @param original_shipping_service the value for order_transaction_seller_discount.original_shipping_service
     *
     * @mbggenerated
     */
    public void setOriginal_shipping_service(String original_shipping_service) {
        this.original_shipping_service = original_shipping_service == null ? null : original_shipping_service.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_transaction_seller_discount.seller_discount
     *
     * @return the value of order_transaction_seller_discount.seller_discount
     *
     * @mbggenerated
     */
    public String getSeller_discount() {
        return seller_discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_transaction_seller_discount.seller_discount
     *
     * @param seller_discount the value for order_transaction_seller_discount.seller_discount
     *
     * @mbggenerated
     */
    public void setSeller_discount(String seller_discount) {
        this.seller_discount = seller_discount == null ? null : seller_discount.trim();
    }
}