package yk.boxri.pojo;

import java.io.Serializable;

public class OrderShippingDetailsShipmentTrackingDetails implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_shipment_tracking_details.order_id
     *
     * @mbggenerated
     */
    public String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_shipment_tracking_details.order_shipping_details_shipment_tracking_details_id
     *
     * @mbggenerated
     */
    public Integer order_shipping_details_shipment_tracking_details_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_shipment_tracking_details.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_shipment_tracking_details.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_shipment_tracking_details.shipment_tracking_number
     *
     * @mbggenerated
     */
    public String shipment_tracking_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_details_shipment_tracking_details.shipping_carrier_used
     *
     * @mbggenerated
     */
    public String shipping_carrier_used;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_shipment_tracking_details.order_id
     *
     * @return the value of order_shipping_details_shipment_tracking_details.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_shipment_tracking_details.order_id
     *
     * @param order_id the value for order_shipping_details_shipment_tracking_details.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_shipment_tracking_details.order_shipping_details_shipment_tracking_details_id
     *
     * @return the value of order_shipping_details_shipment_tracking_details.order_shipping_details_shipment_tracking_details_id
     *
     * @mbggenerated
     */
    public Integer getOrder_shipping_details_shipment_tracking_details_id() {
        return order_shipping_details_shipment_tracking_details_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_shipment_tracking_details.order_shipping_details_shipment_tracking_details_id
     *
     * @param order_shipping_details_shipment_tracking_details_id the value for order_shipping_details_shipment_tracking_details.order_shipping_details_shipment_tracking_details_id
     *
     * @mbggenerated
     */
    public void setOrder_shipping_details_shipment_tracking_details_id(Integer order_shipping_details_shipment_tracking_details_id) {
        this.order_shipping_details_shipment_tracking_details_id = order_shipping_details_shipment_tracking_details_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_shipment_tracking_details.user_id
     *
     * @return the value of order_shipping_details_shipment_tracking_details.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_shipment_tracking_details.user_id
     *
     * @param user_id the value for order_shipping_details_shipment_tracking_details.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_shipment_tracking_details.shop_id
     *
     * @return the value of order_shipping_details_shipment_tracking_details.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_shipment_tracking_details.shop_id
     *
     * @param shop_id the value for order_shipping_details_shipment_tracking_details.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_shipment_tracking_details.shipment_tracking_number
     *
     * @return the value of order_shipping_details_shipment_tracking_details.shipment_tracking_number
     *
     * @mbggenerated
     */
    public String getShipment_tracking_number() {
        return shipment_tracking_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_shipment_tracking_details.shipment_tracking_number
     *
     * @param shipment_tracking_number the value for order_shipping_details_shipment_tracking_details.shipment_tracking_number
     *
     * @mbggenerated
     */
    public void setShipment_tracking_number(String shipment_tracking_number) {
        this.shipment_tracking_number = shipment_tracking_number == null ? null : shipment_tracking_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_details_shipment_tracking_details.shipping_carrier_used
     *
     * @return the value of order_shipping_details_shipment_tracking_details.shipping_carrier_used
     *
     * @mbggenerated
     */
    public String getShipping_carrier_used() {
        return shipping_carrier_used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_details_shipment_tracking_details.shipping_carrier_used
     *
     * @param shipping_carrier_used the value for order_shipping_details_shipment_tracking_details.shipping_carrier_used
     *
     * @mbggenerated
     */
    public void setShipping_carrier_used(String shipping_carrier_used) {
        this.shipping_carrier_used = shipping_carrier_used == null ? null : shipping_carrier_used.trim();
    }
}