package yk.boxri.pojo;

import java.io.Serializable;
import java.util.Date;

public class Shops implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shop_id
     *
     * @mbggenerated
     */
    public Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.user_id
     *
     * @mbggenerated
     */
    public Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.token
     *
     * @mbggenerated
     */
    public String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shop_name
     *
     * @mbggenerated
     */
    public String shop_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.access_token
     *
     * @mbggenerated
     */
    public String access_token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.refresh_token
     *
     * @mbggenerated
     */
    public String refresh_token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.added_date
     *
     * @mbggenerated
     */
    public Date added_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.updated_date
     *
     * @mbggenerated
     */
    public Date updated_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shops
     *
     * @mbggenerated
     */
    public static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shop_id
     *
     * @return the value of shops.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shop_id
     *
     * @param shop_id the value for shops.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.user_id
     *
     * @return the value of shops.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.user_id
     *
     * @param user_id the value for shops.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.token
     *
     * @return the value of shops.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.token
     *
     * @param token the value for shops.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shop_name
     *
     * @return the value of shops.shop_name
     *
     * @mbggenerated
     */
    public String getShop_name() {
        return shop_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shop_name
     *
     * @param shop_name the value for shops.shop_name
     *
     * @mbggenerated
     */
    public void setShop_name(String shop_name) {
        this.shop_name = shop_name == null ? null : shop_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.access_token
     *
     * @return the value of shops.access_token
     *
     * @mbggenerated
     */
    public String getAccess_token() {
        return access_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.access_token
     *
     * @param access_token the value for shops.access_token
     *
     * @mbggenerated
     */
    public void setAccess_token(String access_token) {
        this.access_token = access_token == null ? null : access_token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.refresh_token
     *
     * @return the value of shops.refresh_token
     *
     * @mbggenerated
     */
    public String getRefresh_token() {
        return refresh_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.refresh_token
     *
     * @param refresh_token the value for shops.refresh_token
     *
     * @mbggenerated
     */
    public void setRefresh_token(String refresh_token) {
        this.refresh_token = refresh_token == null ? null : refresh_token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.added_date
     *
     * @return the value of shops.added_date
     *
     * @mbggenerated
     */
    public Date getAdded_date() {
        return added_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.added_date
     *
     * @param added_date the value for shops.added_date
     *
     * @mbggenerated
     */
    public void setAdded_date(Date added_date) {
        this.added_date = added_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.updated_date
     *
     * @return the value of shops.updated_date
     *
     * @mbggenerated
     */
    public Date getUpdated_date() {
        return updated_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.updated_date
     *
     * @param updated_date the value for shops.updated_date
     *
     * @mbggenerated
     */
    public void setUpdated_date(Date updated_date) {
        this.updated_date = updated_date;
    }
}