package yk.boxri.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderTransactionPaymentHoldDetails;



public interface OrderTransactionPaymentHoldDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_payment_hold_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String transaction_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_payment_hold_details
     *
     * @mbggenerated
     */
    int insert(OrderTransactionPaymentHoldDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_payment_hold_details
     *
     * @mbggenerated
     */
    OrderTransactionPaymentHoldDetails selectByPrimaryKey(String transaction_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_payment_hold_details
     *
     * @mbggenerated
     */
    List<OrderTransactionPaymentHoldDetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_payment_hold_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTransactionPaymentHoldDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_payment_hold_details
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderTransactionPaymentHoldDetails> recordLst);
    
    
    
    void mergerBatch(List<OrderTransactionPaymentHoldDetails> recordLst);

    
    
    List<OrderTransactionPaymentHoldDetails> dynamicSelect(List<String> updateOrderList);
}