package yk.boxri.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderTransactionBuyer;



public interface OrderTransactionBuyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_buyer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String transaction_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_buyer
     *
     * @mbggenerated
     */
    int insert(OrderTransactionBuyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_buyer
     *
     * @mbggenerated
     */
    OrderTransactionBuyer selectByPrimaryKey(String transaction_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_buyer
     *
     * @mbggenerated
     */
    List<OrderTransactionBuyer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_buyer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTransactionBuyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_buyer
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderTransactionBuyer> recordLst);
    
    
    void mergerBatch(List<OrderTransactionBuyer> recordLst);

    
    
    List<OrderTransactionBuyer> dynamicSelect(List<String> updateOrderList);

}