package yk.boxri.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderTransactionTaxes;



public interface OrderTransactionTaxesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_taxes
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("transaction_taxes_id") Integer transaction_taxes_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_taxes
     *
     * @mbggenerated
     */
    int deletewithUpdate(List<OrderTransactionTaxes> recordLst);
    
    int insert(OrderTransactionTaxes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_taxes
     *
     * @mbggenerated
     */
    OrderTransactionTaxes selectByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("transaction_taxes_id") Integer transaction_taxes_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_taxes
     *
     * @mbggenerated
     */
    List<OrderTransactionTaxes> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_taxes
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTransactionTaxes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_taxes
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderTransactionTaxes> recordLst);
    
    
    List<OrderTransactionTaxes> dynamicSelect(List<String> updateOrderList);
}