package yk.boxri.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderTransactionVariation;



public interface OrderTransactionVariationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_variation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("transaction_variation_id") Integer transaction_variation_id);

    int deletewithUpdate(List<OrderTransactionVariation> recordLst);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_variation
     *
     * @mbggenerated
     */
    int insert(OrderTransactionVariation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_variation
     *
     * @mbggenerated
     */
    OrderTransactionVariation selectByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("transaction_variation_id") Integer transaction_variation_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_variation
     *
     * @mbggenerated
     */
    List<OrderTransactionVariation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_variation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTransactionVariation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_variation
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderTransactionVariation> recordLst);
    
    
    List<OrderTransactionVariation> dynamicSelect(List<String> updateOrderList);
}