package yk.boxri.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderTransactionShippingDetailsShippingServiceOptions;



public interface OrderTransactionShippingDetailsShippingServiceOptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_shipping_service_options
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("transaction_shipping_details_shipping_service_options_id") Integer transaction_shipping_details_shipping_service_options_id);

    int deletewithUpdate(List<OrderTransactionShippingDetailsShippingServiceOptions> recordLst);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_shipping_service_options
     *
     * @mbggenerated
     */
    int insert(OrderTransactionShippingDetailsShippingServiceOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_shipping_service_options
     *
     * @mbggenerated
     */
    OrderTransactionShippingDetailsShippingServiceOptions selectByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("transaction_shipping_details_shipping_service_options_id") Integer transaction_shipping_details_shipping_service_options_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_shipping_service_options
     *
     * @mbggenerated
     */
    List<OrderTransactionShippingDetailsShippingServiceOptions> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_shipping_service_options
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTransactionShippingDetailsShippingServiceOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_shipping_service_options
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderTransactionShippingDetailsShippingServiceOptions> recordLst);
    
    
    List<OrderTransactionShippingDetailsShippingServiceOptions> dynamicSelect(List<String> updateOrderList);
}