package yk.boxri.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderShippingAddress;



public interface OrderShippingAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String order_id);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_address
     *
     * @mbggenerated
     */
    int insert(OrderShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_address
     *
     * @mbggenerated
     */
    OrderShippingAddress selectByPrimaryKey(String order_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_address
     *
     * @mbggenerated
     */
    List<OrderShippingAddress> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_address
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderShippingAddress> recordLst);
    
    
    void mergerBatch(List<OrderShippingAddress> recordLst);

    
    
    List<OrderShippingAddress> dynamicSelect(List<String> updateOrderList);

}