package yk.boxri.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderPaymentHoldDetails;


public interface OrderPaymentHoldDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_hold_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String order_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_hold_details
     *
     * @mbggenerated
     */
    int insert(OrderPaymentHoldDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_hold_details
     *
     * @mbggenerated
     */
    OrderPaymentHoldDetails selectByPrimaryKey(String order_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_hold_details
     *
     * @mbggenerated
     */
    List<OrderPaymentHoldDetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_hold_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderPaymentHoldDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_hold_details
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderPaymentHoldDetails> recordLst);

    void mergerBatch(List<OrderPaymentHoldDetails> recordLst);
    
    
    List<OrderPaymentHoldDetails> dynamicSelect(List<String> updateOrderList); 

}