package yk.boxri.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderShippingDetails;



public interface OrderShippingDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String order_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details
     *
     * @mbggenerated
     */
    int insert(OrderShippingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details
     *
     * @mbggenerated
     */
    OrderShippingDetails selectByPrimaryKey(String order_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details
     *
     * @mbggenerated
     */
    List<OrderShippingDetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderShippingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderShippingDetails> recordLst);
    
    
    void mergerBatch(List<OrderShippingDetails> recordLst);

    
    
    List<OrderShippingDetails> dynamicSelect(List<String> updateOrderList);

}