package yk.boxri.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderShippingDetailsIntlShippingServiceOption;



public interface OrderShippingDetailsIntlShippingServiceOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("order_id") String order_id, @Param("order_shipping_details_intl_shipping_service_option_id") Integer order_shipping_details_intl_shipping_service_option_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    int insert(OrderShippingDetailsIntlShippingServiceOption record);

    
    int deletewithUpdate(List<OrderShippingDetailsIntlShippingServiceOption> recordLst);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    OrderShippingDetailsIntlShippingServiceOption selectByPrimaryKey(@Param("order_id") String order_id, @Param("order_shipping_details_intl_shipping_service_option_id") Integer order_shipping_details_intl_shipping_service_option_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    List<OrderShippingDetailsIntlShippingServiceOption> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderShippingDetailsIntlShippingServiceOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderShippingDetailsIntlShippingServiceOption> recordLst);
    
    
    List<OrderShippingDetailsIntlShippingServiceOption> dynamicSelect(List<String> updateOrderList);

}