package yk.boxri.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderShippingDetailsShipmentTrackingDetails;



public interface OrderShippingDetailsShipmentTrackingDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("order_id") String order_id, @Param("order_shipping_details_shipment_tracking_details_id") Integer order_shipping_details_shipment_tracking_details_id);

    int deletewithUpdate(List<OrderShippingDetailsShipmentTrackingDetails> recordLst);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    int insert(OrderShippingDetailsShipmentTrackingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    OrderShippingDetailsShipmentTrackingDetails selectByPrimaryKey(@Param("order_id") String order_id, @Param("order_shipping_details_shipment_tracking_details_id") Integer order_shipping_details_shipment_tracking_details_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    List<OrderShippingDetailsShipmentTrackingDetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderShippingDetailsShipmentTrackingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderShippingDetailsShipmentTrackingDetails> recordLst);
    
    List<OrderShippingDetailsShipmentTrackingDetails> dynamicSelect(List<String> updateOrderList);

}