package yk.boxri.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderTransactionShippingDetailsShipmentTrackingDetails;



public interface OrderTransactionShippingDetailsShipmentTrackingDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("transaction_shipping_details_shipment_tracking_details_id") Integer transaction_shipping_details_shipment_tracking_details_id);

    
    int deletewithUpdate(List<OrderTransactionShippingDetailsShipmentTrackingDetails> recordLst);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    int insert(OrderTransactionShippingDetailsShipmentTrackingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    OrderTransactionShippingDetailsShipmentTrackingDetails selectByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("transaction_shipping_details_shipment_tracking_details_id") Integer transaction_shipping_details_shipment_tracking_details_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    List<OrderTransactionShippingDetailsShipmentTrackingDetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTransactionShippingDetailsShipmentTrackingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_shipment_tracking_details
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderTransactionShippingDetailsShipmentTrackingDetails> recordLst);
    
    
    List<OrderTransactionShippingDetailsShipmentTrackingDetails> dynamicSelect(List<String> updateOrderList);
}