package yk.boxri.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderTransactionShippingDetailsIntlShippingServiceOption;



public interface OrderTransactionShippingDetailsIntlShippingServiceOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("transaction_shipping_details_intl_shipping_service_option_id") Integer transaction_shipping_details_intl_shipping_service_option_id);

    
    int deletewithUpdate(List<OrderTransactionShippingDetailsIntlShippingServiceOption> recordLst);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    int insert(OrderTransactionShippingDetailsIntlShippingServiceOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    OrderTransactionShippingDetailsIntlShippingServiceOption selectByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("transaction_shipping_details_intl_shipping_service_option_id") Integer transaction_shipping_details_intl_shipping_service_option_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    List<OrderTransactionShippingDetailsIntlShippingServiceOption> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTransactionShippingDetailsIntlShippingServiceOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_shipping_details_intl_shipping_service_option
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderTransactionShippingDetailsIntlShippingServiceOption> recordLst);
    
    
    List<OrderTransactionShippingDetailsIntlShippingServiceOption> dynamicSelect(List<String> updateOrderList);
}