package yk.boxri.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderTransactionMultilegShippingDetails;



public interface OrderTransactionMultilegShippingDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_multileg_shipping_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String transaction_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_multileg_shipping_details
     *
     * @mbggenerated
     */
    int insert(OrderTransactionMultilegShippingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_multileg_shipping_details
     *
     * @mbggenerated
     */
    OrderTransactionMultilegShippingDetails selectByPrimaryKey(String transaction_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_multileg_shipping_details
     *
     * @mbggenerated
     */
    List<OrderTransactionMultilegShippingDetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_multileg_shipping_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTransactionMultilegShippingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_multileg_shipping_details
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderTransactionMultilegShippingDetails> recordLst);
    
    
    void mergerBatch(List<OrderTransactionMultilegShippingDetails> recordLst);

    
    
    List<OrderTransactionMultilegShippingDetails> dynamicSelect(List<String> updateOrderList);
}