package yk.boxri.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderTransactionItem;


public interface OrderTransactionItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("item_id") String item_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_item
     *
     * @mbggenerated
     */
    int insert(OrderTransactionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_item
     *
     * @mbggenerated
     */
    OrderTransactionItem selectByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("item_id") String item_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_item
     *
     * @mbggenerated
     */
    List<OrderTransactionItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTransactionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_item
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderTransactionItem> recordLst);
    
    
    void mergerBatch(List<OrderTransactionItem> recordLst);

    
    
    List<OrderTransactionItem> dynamicSelect(List<String> updateOrderList);

}