package yk.boxri.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderTransactionMonetaryDetailsRefunds;



public interface OrderTransactionMonetaryDetailsRefundsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_monetary_details_refunds
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("transaction_monetary_details_refund_id") Integer transaction_monetary_details_refund_id);

    
    int deletewithUpdate(List<OrderTransactionMonetaryDetailsRefunds> recordLst);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_monetary_details_refunds
     *
     * @mbggenerated
     */
    int insert(OrderTransactionMonetaryDetailsRefunds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_monetary_details_refunds
     *
     * @mbggenerated
     */
    OrderTransactionMonetaryDetailsRefunds selectByPrimaryKey(@Param("transaction_id") String transaction_id, @Param("transaction_monetary_details_refund_id") Integer transaction_monetary_details_refund_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_monetary_details_refunds
     *
     * @mbggenerated
     */
    List<OrderTransactionMonetaryDetailsRefunds> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_monetary_details_refunds
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTransactionMonetaryDetailsRefunds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_transaction_monetary_details_refunds
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderTransactionMonetaryDetailsRefunds> recordLst);
    
    
    List<OrderTransactionMonetaryDetailsRefunds> dynamicSelect(List<String> updateOrderList);
}