package yk.boxri.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderPickupDetails;



public interface OrderPickupDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pickup_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("order_id") String order_id, @Param("order_pickup_details_id") Integer order_pickup_details_id);

    int deletewithUpdate(List<OrderPickupDetails> recordLst);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pickup_details
     *
     * @mbggenerated
     */
    int insert(OrderPickupDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pickup_details
     *
     * @mbggenerated
     */
    OrderPickupDetails selectByPrimaryKey(@Param("order_id") String order_id, @Param("order_pickup_details_id") Integer order_pickup_details_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pickup_details
     *
     * @mbggenerated
     */
    List<OrderPickupDetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pickup_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderPickupDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pickup_details
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderPickupDetails> recordLst);
    
    List<OrderPickupDetails> dynamicSelect(List<String> updateOrderList);

}