package yk.boxri.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderMonetaryDetailsRefunds;


public interface OrderMonetaryDetailsRefundsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_monetary_details_refunds
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("order_id") String order_id, @Param("order_monetary_details_refunds_id") Integer order_monetary_details_refunds_id);

    
    int deletewithUpdate(List<OrderMonetaryDetailsRefunds> recordLst);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_monetary_details_refunds
     *
     * @mbggenerated
     */
    int insert(OrderMonetaryDetailsRefunds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_monetary_details_refunds
     *
     * @mbggenerated
     */
    OrderMonetaryDetailsRefunds selectByPrimaryKey(@Param("order_id") String order_id, @Param("order_monetary_details_refunds_id") Integer order_monetary_details_refunds_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_monetary_details_refunds
     *
     * @mbggenerated
     */
    List<OrderMonetaryDetailsRefunds> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_monetary_details_refunds
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderMonetaryDetailsRefunds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_monetary_details_refunds
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderMonetaryDetailsRefunds> recordLst);
    
    
    List<OrderMonetaryDetailsRefunds> dynamicSelect(List<String> updateOrderList);
}