package yk.boxri.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import yk.boxri.pojo.OrderMonetaryDetailsPayments;


public interface OrderMonetaryDetailsPaymentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_monetary_details_payments
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("order_id") String order_id, @Param("order_monetary_details_payments_id") Integer order_monetary_details_payments_id);

    
    int deletewithUpdate(List<OrderMonetaryDetailsPayments> recordLst);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_monetary_details_payments
     *
     * @mbggenerated
     */
    int insert(OrderMonetaryDetailsPayments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_monetary_details_payments
     *
     * @mbggenerated
     */
    OrderMonetaryDetailsPayments selectByPrimaryKey(@Param("order_id") String order_id, @Param("order_monetary_details_payments_id") Integer order_monetary_details_payments_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_monetary_details_payments
     *
     * @mbggenerated
     */
    List<OrderMonetaryDetailsPayments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_monetary_details_payments
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderMonetaryDetailsPayments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_monetary_details_payments
     *
     * @mbggenerated
     */
    void insertBatch(List<OrderMonetaryDetailsPayments> recordLst);
    
    
    List<OrderMonetaryDetailsPayments> dynamicSelect(List<String> updateOrderList); 
}