package yk.boxri.dao;


import java.util.List;

import org.springframework.stereotype.Repository;

import yk.boxri.pojo.Shops;

public interface ShopsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer shop_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated
     */
    int insert(Shops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated
     */
    Shops selectByPrimaryKey(Integer shop_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated
     */
    List<Shops> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated
     */
    void insertBatch(List<Shops> recordLst);
}